import{getDb,getSettings}from"../../../../lib/db";
function firstName(n:string){return n.trim().split(/\s+/)[0]||"there"}
function draft(x:any){
 const engineering=x.division==="Engineering";
 const need=String(x.service||(engineering?"mechanical engineering and design support":"software and workflow automation")).trim();
 const subject=engineering?`${x.company} - engineering capacity support`:`${x.company} - software automation support`;
 const opening=engineering
  ?`I’m reaching out because we identified current activity at ${x.company} related to ${need.toLowerCase()}. Arch Engineering Services helps engineering teams add experienced design capacity when schedules are tight, projects peak, or internal resources are committed elsewhere.`
  :`I’m reaching out because we identified current activity at ${x.company} related to ${need.toLowerCase()}. Arch Engineering Services helps teams replace manual, disconnected processes with practical software and automation built around the way their business actually operates.`;
 const capability=engineering
  ?`We can support mechanical design and detailing, Inventor/SolidWorks/AutoCAD, fabrication and manufacturing drawings, BOMs, CAD/iLogic automation, reverse engineering, and overflow project work. We can step in for a defined package of work or operate as an extension of your engineering team.`
  :`We build custom business applications, workflow automation, integrations/APIs, dashboards, customer and internal portals, CRM/operations tools, and web/mobile applications. The focus is measurable: reduce repetitive work, improve visibility, and connect processes that currently require manual handoffs.`;
 const close=engineering
  ?`If ${x.company} has a current design backlog, upcoming project, or a need for additional engineering bandwidth, I’d welcome a short conversation. I can also send a concise capability overview and relevant examples for your review.`
  :`If ${x.company} has a workflow that is still heavily manual, an integration gap, or an application initiative that needs additional development capacity, I’d welcome a short conversation. I can also send a concise capability overview and relevant examples for your review.`;
 const body=`Hi ${firstName(x.contact_name)},\n\n${opening}\n\n${capability}\n\n${close}\n\nWould a brief 15-minute conversation next week be worthwhile?\n\nBest regards,\nSridhar Kota\nArch Engineering Services\narchengineeringservices.com\n\nIf you prefer not to receive further outreach from us, reply and we will remove you from future messages.`;
 return{subject,body};
}
export async function POST(){try{const s=await getSettings();if(!s.dryRun)return Response.json({ok:false,error:"Draft preparation is locked to Dry Run."},{status:409});if(!s.senderEmail)return Response.json({ok:false,error:"Configure sender_email before preparing outreach."},{status:400});const db=getDb();const leads=(await db.prepare(`SELECT id,company,division,service,contact_name,contact_email FROM leads WHERE qualification_status='Qualified' AND outreach_status='Ready for Review' AND email_verified=1 ORDER BY ai_score DESC LIMIT ?`).bind(s.totalLimit).all<any>()).results;let queued=0,skipped=0;for(const x of leads){const sup=await db.prepare(`SELECT id FROM suppressions WHERE lower(email)=lower(?) LIMIT 1`).bind(x.contact_email).first<any>();if(sup){skipped++;continue}const prior=await db.prepare(`SELECT id FROM outreach_messages WHERE lead_id=? AND status IN ('Queued','Approved','Sent') LIMIT 1`).bind(x.id).first<any>();if(prior){skipped++;continue}const d=draft(x);await db.prepare(`INSERT INTO outreach_messages(lead_id,division,recipient,sender,subject,body,status,attempt_number) VALUES(?,?,?,?,?,?,'Queued',1)`).bind(x.id,x.division,x.contact_email,s.senderEmail,d.subject,d.body).run();await db.prepare(`UPDATE leads SET outreach_status='Draft Ready',updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(x.id).run();queued++;}return Response.json({ok:true,dryRun:true,emailSending:false,queued,skipped,message:`${queued} personalized outreach drafts prepared for approval. No email sent.`});}catch(e){return Response.json({ok:false,error:e instanceof Error?e.message:"Draft preparation failed"},{status:500});}}
