import type{Division}from"./discovery";
export type ApolloProspect={company:string;division:Division;service:string;contactName:string;contactEmail:string;contactPhone:string;website?:string;title?:string};
type Criteria={division:Division;service:string;keywords:string[];titles:string[];employeeRanges:string[];limit:number};
type Org={name?:string;website_url?:string;primary_domain?:string};type Person={id?:string;name?:string;email?:string;sanitized_phone?:string;title?:string;organization?:Org};
async function call<T>(path:string,body:Record<string,unknown>){const key=process.env.APOLLO_API_KEY;if(!key)return{ok:false as const,error:"APOLLO_API_KEY is not configured"};try{const r=await fetch(`https://api.apollo.io/v1${path}`,{method:"POST",headers:{"Content-Type":"application/json","X-Api-Key":key},body:JSON.stringify(body),cache:"no-store"});if(!r.ok)return{ok:false as const,error:`Apollo API ${r.status}: ${(await r.text()).slice(0,250)}`};return{ok:true as const,data:await r.json() as T}}catch(e){return{ok:false as const,error:e instanceof Error?e.message:"Apollo request failed"}}
}
function safeEmail(v?:string){const e=String(v||"").trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&!e.includes("not_unlocked")&&!/(gmail|yahoo|hotmail|outlook)\.com$/i.test(e)?e:""}
export const ENGINEERING:Criteria={division:"Engineering",service:"Mechanical CAD, drafting, design, automation, or PE support",keywords:["manufacturing","metal fabrication","equipment manufacturing","custom machinery","material handling","industrial equipment","mechanical contractor","process equipment","industrial automation"],titles:["Engineering Manager","Mechanical Engineering Manager","Design Engineering Manager","Design Manager","Director of Engineering","Manufacturing Engineering Manager","Project Engineering Manager","Operations Manager","Plant Manager","General Manager","Owner","President"],employeeRanges:["1,500"],limit:25};
export const SOFTWARE:Criteria={division:"Software",service:"Custom software, websites, portals, integrations, CRM, scheduling, or workflow automation",keywords:["manufacturing","field service","contractor","construction","HVAC","plumbing","electrical","distribution","logistics","property management","landscaping","professional services"],titles:["Owner","President","Chief Operating Officer","Operations Manager","General Manager","IT Manager","IT Director","Director of Technology","Director of Operations","Business Systems Director"],employeeRanges:["1,200"],limit:10};
export async function findApolloProspects(c:Criteria){const s=await call<{people?:Person[]}>("/mixed_people/search",{q_organization_keyword_tags:c.keywords,person_titles:c.titles,organization_num_employees_ranges:c.employeeRanges,person_locations:["United States"],page:1,per_page:Math.min(100,c.limit*3)});if(!s.ok)return{prospects:[] as ApolloProspect[],error:s.error};const prospects:ApolloProspect[]=[];const seen=new Set<string>();for(const p of s.data.people||[]){if(prospects.length>=c.limit)break;if(!p.id)continue;const m=await call<{person?:Person}>("/people/match",{id:p.id,reveal_personal_emails:false});if(!m.ok)continue;const person=m.data.person||p,email=safeEmail(person.email);const org=person.organization||p.organization;if(!email||!org?.name||seen.has(email))continue;seen.add(email);const website=org.website_url||(org.primary_domain?`https://${org.primary_domain}`:undefined);prospects.push({company:org.name,division:c.division,service:c.service,contactName:person.name||p.name||"",contactEmail:email,contactPhone:person.sanitized_phone||p.sanitized_phone||"",website,title:person.title||p.title})}return{prospects};}
