import type{Division}from"./discovery";
export type ApolloProspect={company:string;division:Division;service:string;contactName:string;contactEmail:string;contactPhone:string;website?:string;title?:string};
type Criteria={division:Division;service:string;keywords:string[];titles:string[];employeeRanges:string[];limit:number};
type Org={name?:string;website_url?:string;primary_domain?:string};type Person={id?:string;name?:string;email?:string;email_status?:string;sanitized_phone?:string;title?:string;organization?:Org};
async function call<T>(path:string,body:Record<string,unknown>){const key=process.env.APOLLO_API_KEY;if(!key)return{ok:false as const,error:"APOLLO_API_KEY is not configured"};try{const r=await fetch(`https://api.apollo.io/v1${path}`,{method:"POST",headers:{"Content-Type":"application/json","X-Api-Key":key},body:JSON.stringify(body),cache:"no-store"});if(!r.ok)return{ok:false as const,error:`Apollo API ${r.status}: ${(await r.text()).slice(0,250)}`};return{ok:true as const,data:await r.json() as T}}catch(e){return{ok:false as const,error:e instanceof Error?e.message:"Apollo request failed"}}}
function safeEmail(v?:string){const e=String(v||"").trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&!e.includes("not_unlocked")&&!/(gmail|yahoo|hotmail|outlook)\.com$/i.test(e)?e:""}
function companyKey(org?:Org,name?:string){const domain=String(org?.primary_domain||org?.website_url||"").toLowerCase().replace(/^https?:\/\//,"").replace(/^www\./,"").split(/[/?#]/)[0];return domain||String(name||org?.name||"").toLowerCase().replace(/[^a-z0-9]/g,"")}
function roleScore(d:Division,title?:string){const t=String(title||"").toLowerCase();const groups=d==="Engineering"?[["director of engineering","engineering director","vp engineering","vice president engineering"],["engineering manager","mechanical engineering manager","design engineering manager","manufacturing engineering manager","project engineering manager"],["design manager","plant manager"],["president","owner"],["operations manager","general manager"]]:[["it director","director of technology","business systems director","chief information","chief technology"],["chief operating officer","coo","director of operations"],["it manager","operations manager"],["president","owner"],["general manager"]];for(let i=0;i<groups.length;i++)if(groups[i].some(x=>t.includes(x)))return 100-i*10;return 10}
export const ENGINEERING:Criteria={division:"Engineering",service:"Mechanical CAD, drafting, design, automation, or PE support",keywords:["manufacturing","metal fabrication","equipment manufacturing","custom machinery","material handling","industrial equipment","mechanical contractor","process equipment","industrial automation"],titles:["Engineering Manager","Mechanical Engineering Manager","Design Engineering Manager","Design Manager","Director of Engineering","Manufacturing Engineering Manager","Project Engineering Manager","Operations Manager","Plant Manager","General Manager","Owner","President"],employeeRanges:["1,500"],limit:25};
export const SOFTWARE:Criteria={division:"Software",service:"Custom software, websites, portals, integrations, CRM, scheduling, or workflow automation",keywords:["manufacturing","field service","contractor","construction","HVAC","plumbing","electrical","distribution","logistics","property management","landscaping","professional services"],titles:["Owner","President","Chief Operating Officer","Operations Manager","General Manager","IT Manager","IT Director","Director of Technology","Director of Operations","Business Systems Director"],employeeRanges:["1,200"],limit:10};
function prospect(c:Criteria,p:Person,email:string):ApolloProspect|null{const org=p.organization;if(!email||!org?.name||!p.name)return null;return{company:org.name,division:c.division,service:c.service,contactName:p.name,contactEmail:email,contactPhone:p.sanitized_phone||"",website:org.website_url||(org.primary_domain?`https://${org.primary_domain}`:undefined),title:p.title}}
export async function findApolloProspects(c:Criteria){const s=await call<{people?:Person[]}>("/mixed_people/api_search",{q_organization_keyword_tags:c.keywords,person_titles:c.titles,organization_num_employees_ranges:c.employeeRanges,person_locations:["United States"],page:1,per_page:100});if(!s.ok)return{prospects:[] as ApolloProspect[],error:s.error};const ranked=(s.data.people||[]).filter(p=>p.id&&p.organization?.name).sort((a,b)=>roleScore(c.division,b.title)-roleScore(c.division,a.title));const unique:Person[]=[];const companies=new Set<string>();for(const p of ranked){const k=companyKey(p.organization,p.organization?.name);if(!k||companies.has(k))continue;companies.add(k);unique.push(p);if(unique.length>=50)break}const prospects:ApolloProspect[]=[];const accepted=new Set<string>();const fallback:Person[]=[];for(const p of unique){const email=safeEmail(p.email);const status=String(p.email_status||"").toLowerCase();const direct=email&&(!status||status==="verified"||status==="valid")?prospect(c,p,email):null;if(direct){const k=companyKey(p.organization,p.organization?.name);accepted.add(k);prospects.push(direct);if(prospects.length>=c.limit)break}else fallback.push(p)}for(let i=0;i<fallback.length&&prospects.length<c.limit&&i<20;i+=5){const batch=fallback.slice(i,i+5);const matched=await Promise.all(batch.map(async p=>{const m=await call<{person?:Person}>("/people/match",{id:p.id,reveal_personal_emails:false});if(!m.ok)return null;const person=m.data.person||p,email=safeEmail(person.email),org=person.organization||p.organization,k=companyKey(org,org?.name);if(!email||!org?.name||accepted.has(k))return null;if(person.email_status&&!["verified","valid"].includes(person.email_status.toLowerCase()))return null;const out=prospect(c,{...person,organization:org},email);if(out)accepted.add(k);return out}));for(const p of matched)if(p&&prospects.length<c.limit)prospects.push(p)}return{prospects};}
