import type{Division}from"./discovery";
export type ApolloProspect={company:string;division:Division;service:string;contactName:string;contactEmail:string;contactPhone:string;website?:string;title?:string};
type Criteria={division:Division;service:string;titles:string[];employeeRanges:string[];limit:number};
type Org={name?:string;website_url?:string;primary_domain?:string};type Person={id?:string;person_id?:string;name?:string;first_name?:string;last_name?:string;email?:string;email_status?:string;sanitized_phone?:string;title?:string;organization?:Org;organization_name?:string;organization_id?:string};
async function post<T>(path:string,params:Record<string,unknown>,jsonBody?:unknown){const key=process.env.APOLLO_API_KEY;if(!key)return{ok:false as const,error:"APOLLO_API_KEY is not configured"};try{const q=new URLSearchParams();for(const[k,v]of Object.entries(params)){if(v==null)continue;if(Array.isArray(v))for(const x of v)q.append(`${k}[]`,String(x));else q.set(k,String(v))}const r=await fetch(`https://api.apollo.io/api/v1${path}${q.size?`?${q}`:""}`,{method:"POST",headers:{accept:"application/json","Content-Type":"application/json","Cache-Control":"no-cache","x-api-key":key},body:jsonBody?JSON.stringify(jsonBody):undefined,cache:"no-store"});if(!r.ok)return{ok:false as const,error:`Apollo API ${r.status}: ${(await r.text()).slice(0,300)}`};return{ok:true as const,data:await r.json() as T}}catch(e){return{ok:false as const,error:e instanceof Error?e.message:"Apollo request failed"}}}
function safeEmail(v?:string){const e=String(v||"").trim().toLowerCase();return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e)&&!e.includes("not_unlocked")&&!/(gmail|yahoo|hotmail|outlook)\.com$/i.test(e)?e:""}
function orgOf(p:Person):Org|undefined{return p.organization||((p.organization_name)?{name:p.organization_name}:undefined)}
function companyKey(p:Person){const org=orgOf(p);return String(org?.primary_domain||org?.website_url||p.organization_id||org?.name||"").toLowerCase().replace(/^https?:\/\//,"").replace(/^www\./,"").replace(/[^a-z0-9.]/g,"")}
function roleScore(d:Division,title?:string){const t=String(title||"").toLowerCase();const groups=d==="Engineering"?[["director of engineering","engineering director","vp engineering"],["engineering manager","mechanical engineering manager","design engineering manager","manufacturing engineering manager","project engineering manager"],["design manager","plant manager"],["president","owner"]]:[["it director","director of technology","business systems director","chief information","chief technology"],["chief operating officer","coo","director of operations"],["it manager","operations manager"],["president","owner"],["general manager"]];for(let i=0;i<groups.length;i++)if(groups[i].some(x=>t.includes(x)))return 100-i*10;return 10}
export const ENGINEERING:Criteria={division:"Engineering",service:"Mechanical CAD, drafting, design, automation, or PE support",titles:["Engineering Manager","Mechanical Engineering Manager","Design Engineering Manager","Director of Engineering","Manufacturing Engineering Manager","Project Engineering Manager","Design Manager","Plant Manager","Owner","President"],employeeRanges:["1,500"],limit:25};
export const SOFTWARE:Criteria={division:"Software",service:"Custom software, websites, portals, integrations, CRM, scheduling, or workflow automation",titles:["Owner","President","Chief Operating Officer","Operations Manager","General Manager","IT Manager","IT Director","Director of Technology","Director of Operations","Business Systems Director"],employeeRanges:["1,200"],limit:10};
function prospect(c:Criteria,p:Person,fallback?:Person):ApolloProspect|null{const org=orgOf(p)||orgOf(fallback||{}),email=safeEmail(p.email),name=p.name||[p.first_name,p.last_name].filter(Boolean).join(" ")||fallback?.name||[fallback?.first_name,fallback?.last_name].filter(Boolean).join(" ");if(!email||!org?.name||!name)return null;if(p.email_status&&!['verified','valid'].includes(p.email_status.toLowerCase()))return null;return{company:org.name,division:c.division,service:c.service,contactName:name,contactEmail:email,contactPhone:p.sanitized_phone||"",website:org.website_url||(org.primary_domain?`https://${org.primary_domain}`:undefined),title:p.title||fallback?.title}}
export async function findApolloProspects(c:Criteria){const s=await post<{people?:Person[]}>("/mixed_people/api_search",{person_titles:c.titles,include_similar_titles:true,person_locations:["United States"],organization_num_employees_ranges:c.employeeRanges,page:1,per_page:100});if(!s.ok)return{prospects:[] as ApolloProspect[],error:s.error,searchCount:0,uniqueCount:0,matchAttempts:0};const people=s.data.people||[];const ranked=people.filter(p=>p.id||p.person_id).sort((a,b)=>roleScore(c.division,b.title)-roleScore(c.division,a.title));const unique:Person[]=[];const companies=new Set<string>();for(const p of ranked){const k=companyKey(p)||String(p.id||p.person_id);if(companies.has(k))continue;companies.add(k);unique.push(p);if(unique.length>=Math.min(c.limit,8))break}const prospects:ApolloProspect[]=[];let attempts=0;for(const p of unique){attempts++;const m=await post<{person?:Person}>("/people/match",{}, {id:p.id||p.person_id,reveal_personal_emails:false,reveal_phone_number:false});if(!m.ok)continue;const out=prospect(c,m.data.person||p,p);if(out)prospects.push(out)}return{prospects,searchCount:people.length,uniqueCount:unique.length,matchAttempts:attempts};}
