import type{DiscoveryCandidateInput,Division}from"./discovery";
const engineeringNeeds=["CAD drafting engineering support RFP RFQ","mechanical design contractor RFP RFQ","fabrication drawings engineering consultant bid","plant expansion engineering design consultant","Autodesk Inventor CAD contractor"];
const softwareNeeds=["software development RFP RFQ","application modernization implementation partner RFP","system integration software vendor solicitation","workflow automation software contractor RFP","customer portal application development RFP"];
function decode(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function host(u:string){try{return new URL(u).hostname.replace(/^www\./,"").toLowerCase()}catch{return""}}
function companyName(title:string,url:string){const h=host(url),clean=title.split(/[|–—-]/)[0].replace(/\b(rfp|rfq|request for proposals?|request for quotes?|solicitation|bid opportunity)\b/ig,"").trim();return clean.length>=3&&clean.length<=100?clean:h}
function service(d:Division,text:string){const t=text.toLowerCase();if(d==="Engineering"){if(/inventor|cad|draft|drawing/.test(t))return"CAD / drafting support";if(/plant|facility|structural|steel/.test(t))return"Plant / structural engineering support";if(/fabricat|shop drawing/.test(t))return"Fabrication / shop drawings";return"Mechanical engineering support"}if(/modern|legacy|migration/.test(t))return"Legacy modernization / digital transformation";if(/integrat|api/.test(t))return"Integration / API automation";if(/workflow|process automation/.test(t))return"Workflow / business process automation";return"Custom software / internal tools"}
async function ddg(q:string){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{"User-Agent":"Mozilla/5.0 (compatible; ArchLeadAI/1.0)",Accept:"text/html"},cache:"no-store"});if(!r.ok)return[];const html=await r.text(),blocks=html.split(/result__body/i).slice(1,11),out:{url:string;title:string;text:string}[]=[];for(const b of blocks){const a=b.match(/href="([^"]+)"[^>]*class="[^"]*result__a[^>]*>([\s\S]*?)<\/a>/i)||b.match(/class="[^"]*result__a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;let url=decode(a[1]);try{const u=new URL(url,"https://duckduckgo.com"),x=u.searchParams.get("uddg");if(x)url=decodeURIComponent(x)}catch{}out.push({url,title:decode(a[2]),text:decode(b.slice(0,2600))})}return out}catch{return[]}}
export async function searchBuyerIntent(d:Division){const queries=d==="Engineering"?engineeringNeeds:softwareNeeds,out:DiscoveryCandidateInput[]=[],seen=new Set<string>();for(const q of queries){for(const r of await ddg(q)){if(!/^https?:/i.test(r.url)||seen.has(r.url))continue;seen.add(r.url);const text=`${r.title} ${r.text}`,low=text.toLowerCase();if(!/(rfp|rfq|request for proposal|request for quote|solicitation|invitation to bid|seeking vendor|seeking contractor|bid opportunity|procurement|implementation partner|contractor|consultant)/i.test(low))continue;if(/(template|sample rfp|how to write|definition|what is an rfp|job board|career)/i.test(low))continue;const co=companyName(r.title,r.url);out.push({company:co,division:d,service:service(d,text),website:`https://${host(r.url)}`,sourceName:`Public Buyer Intent — ${d}`,sourceUrl:r.url,evidence:`Public buyer-intent result: ${text.slice(0,1400)}`})}if(out.length>=40)break}return out.slice(0,40)}
