import type{DiscoveryCandidateInput,Division}from"./discovery";
const engineeringNeeds=["mechanical engineering RFP RFQ consultant","CAD drafting design RFP RFQ","fabrication drawings engineering bid","plant expansion engineering design","new production line mechanical design","equipment development manufacturing engineering","new product development mechanical design","facility expansion engineering project","industrial equipment design project"];
const softwareNeeds=["software development RFP RFQ","custom application development RFP","application modernization project","system integration implementation project","workflow automation initiative","customer portal development project","legacy system replacement","digital transformation initiative","enterprise application modernization"];
const portalHosts=/(globaltenders|tendersontime|bidnet|bidprime|bidbanana|bidmorning|govcb|highergov|instantmarkets|rfpdb|rfpplanet|governmentbids|findrfp|bidsync|demandstar|bonfirehub|opengov|planetbids|publicpurchase|ionwave|procureware|vendorregistry)/i;
const providerText=/(we provide engineering services|our engineering services|engineering consultants|design consultants|cad services|drafting services|software development company|our software development services|technology consulting services|custom software company|engineering design services|steel detailing services|fabrication drawing services)/i;
const contentText=/(free template|proposal template|download template|blog|article|guide to|how to|key to|tips for|what is|send drawings for|accurate quote|case study)/i;
const buyerWords=/(rfp|rfq|request for proposal|request for quote|invitation to bid|solicitation|seeking (?:a )?(?:vendor|contractor|consultant)|requesting proposals|accepting proposals|bid opportunity|procurement|outsourc|subcontract|staff augmentation)/i;
const projectRx={Engineering:/(plant expansion|facility expansion|new facility|new production line|capital project|equipment development|equipment design|product development|new product|manufacturing project|mechanical design|cad|drafting|fabrication drawing|shop drawing|structural steel|industrial equipment)/i,Software:/(application modernization|legacy system|system replacement|implementation project|integration project|digital transformation|workflow automation|customer portal|crm implementation|enterprise application|system upgrade|platform upgrade|cloud migration|business systems)/i};
const serviceRx={Engineering:/(mechanical|cad|draft|drawing|fabrication|plant|equipment|machine|structural|steel|inventor|solidworks|autocad|engineering design|manufacturing engineering)/i,Software:/(software|application|system integration|workflow|automation|portal|crm|modernization|migration|digital transformation|web application|mobile application|business systems)/i};
function decode(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function host(u:string){try{return new URL(u).hostname.replace(/^www\./,"").toLowerCase()}catch{return""}}
function brandFromHost(h:string){const first=h.split(".")[0].replace(/[-_]/g," ").trim();return first.length>=3?first.replace(/\b\w/g,c=>c.toUpperCase()):""}
function meta(html:string,rx:RegExp){const m=html.match(rx);return m?decode(m[1]):""}
function companyFromOfficialPage(html:string,url:string){const h=host(url),brand=brandFromHost(h);const og=meta(html,/<meta[^>]+property=["']og:site_name["'][^>]+content=["']([^"']+)["']/i)||meta(html,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:site_name["']/i);const app=meta(html,/<meta[^>]+name=["']application-name["'][^>]+content=["']([^"']+)["']/i)||meta(html,/<meta[^>]+content=["']([^"']+)["'][^>]+name=["']application-name["']/i);const candidates=[og,app,brand].map(x=>x.replace(/\s*[|–—].*$/," ").trim()).filter(x=>x.length>=3&&x.length<=80&&!contentText.test(x)&&!serviceRx.Engineering.test(x)&&!serviceRx.Software.test(x));return candidates[0]||brand}
function service(d:Division,text:string){const t=text.toLowerCase();if(d==="Engineering"){if(/inventor|solidworks|autocad|cad|draft|drawing/.test(t))return"CAD / drafting support";if(/plant|facility|structural|steel/.test(t))return"Plant / structural engineering support";if(/fabricat|shop drawing/.test(t))return"Fabrication / shop drawings";if(/product development|equipment development|equipment design/.test(t))return"Product / equipment design support";return"Mechanical engineering support"}if(/modern|legacy|migration|system replacement/.test(t))return"Legacy modernization / digital transformation";if(/integrat|api/.test(t))return"Integration / API automation";if(/workflow|process automation/.test(t))return"Workflow / business process automation";if(/portal|crm/.test(t))return"CRM / portal development";return"Custom software / internal tools"}
async function ddg(q:string){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36",Accept:"text/html","Accept-Language":"en-US,en;q=0.9"},cache:"no-store"});if(!r.ok)return[];const html=await r.text(),blocks=html.split(/result__body/i).slice(1,13),out:{url:string;title:string;text:string}[]=[];for(const b of blocks){const a=b.match(/href="([^"]+)"[^>]*class="[^"]*result__a[^>]*>([\s\S]*?)<\/a>/i)||b.match(/class="[^"]*result__a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;let url=decode(a[1]);try{const u=new URL(url,"https://duckduckgo.com"),x=u.searchParams.get("uddg");if(x)url=decodeURIComponent(x)}catch{}out.push({url,title:decode(a[2]),text:decode(b.slice(0,3000))})}return out}catch{return[]}}
function isPortal(u:string,t:string){return portalHosts.test(host(u))||/(search .*bids|government contracts|daily bid alerts|bid database|tender alerts|procurement platform|business directory|supplier directory)/i.test(t)}
async function confirmResult(r:{url:string;title:string;text:string},d:Division){const summary=`${r.title} ${r.text}`;if(isPortal(r.url,summary)||contentText.test(r.title)||!serviceRx[d].test(summary)||providerText.test(summary))return null;const snippetIntent=buyerWords.test(summary),snippetProject=projectRx[d].test(summary);if(!snippetIntent&&!snippetProject)return null;try{const res=await fetch(r.url,{headers:{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36",Accept:"text/html,application/xhtml+xml","Accept-Language":"en-US,en;q=0.9"},redirect:"follow",cache:"no-store",signal:AbortSignal.timeout(8000)});if(!res.ok)return null;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return null;const html=(await res.text()).slice(0,180000),body=decode(html),combined=`${summary} ${body.slice(0,26000)}`,finalUrl=res.url||r.url;if(isPortal(finalUrl,combined)||providerText.test(body.slice(0,18000))||contentText.test(r.title))return null;if(!serviceRx[d].test(combined))return null;const explicitBuyer=buyerWords.test(combined),projectSignal=projectRx[d].test(combined);if(!explicitBuyer&&!projectSignal)return null;const h=host(finalUrl),company=companyFromOfficialPage(html,finalUrl);if(!company||company.length<3)return null;const titleNorm=r.title.toLowerCase(),companyNorm=company.toLowerCase();const identityEvidence=body.toLowerCase().includes(companyNorm)||titleNorm.includes(companyNorm)||companyNorm.includes(brandFromHost(h).toLowerCase());if(!identityEvidence)return null;return{company,url:finalUrl,text:combined.slice(0,6000),explicitBuyer,projectSignal}}
catch{return null}}
export async function searchBuyerIntent(d:Division){const queries=d==="Engineering"?engineeringNeeds:softwareNeeds,out:DiscoveryCandidateInput[]=[],seen=new Set<string>(),domains=new Set<string>();for(const q of queries){for(const r of await ddg(q)){if(!/^https?:/i.test(r.url)||seen.has(r.url))continue;seen.add(r.url);const c=await confirmResult(r,d);if(!c)continue;const h=host(c.url),key=`${h}|${service(d,c.text)}`;if(domains.has(key))continue;domains.add(key);const kind=c.explicitBuyer?"A — explicit buyer opportunity":"B — strong-fit work signal";out.push({company:c.company,division:d,service:service(d,c.text),website:`https://${h}`,sourceName:`${kind} — ${d}`,sourceUrl:c.url,evidence:`${kind}. Verified company-domain source shows relevant ${d.toLowerCase()} work that Arch may support. ${c.text.slice(0,1800)}`});if(out.length>=40)break}if(out.length>=40)break}return out}
