import type{DiscoveryCandidateInput,Division}from"./discovery";
const engineeringNeeds=["Missouri manufacturer custom machinery equipment","St Louis industrial manufacturer fabrication equipment","Missouri OEM material handling equipment","Kansas City manufacturer process equipment","Midwest custom machine builder manufacturer","Missouri steel fabricator industrial equipment","Missouri plastics manufacturer production expansion","Midwest food process equipment manufacturer","Missouri manufacturing facility expansion equipment"];
const softwareNeeds=["Missouri manufacturer digital transformation","St Louis manufacturer production dashboard software","Missouri business workflow automation project","Midwest manufacturer legacy system modernization","Missouri field service company scheduling software","St Louis manufacturing document control system","Missouri manufacturer quoting estimating software","Midwest industrial company customer portal project"];
const blockedHosts=/(globaltenders|tendersontime|biddetail|rfpmart|bidnet|bidprime|bidbanana|bidmorning|govcb|highergov|instantmarkets|rfpdb|rfpplanet|governmentbids|findrfp|bidsync|demandstar|bonfirehub|opengov|planetbids|publicpurchase|ionwave|procureware|vendorregistry|wonit\.ai|app\.wonit)/i;
const invalidText=/(tender portal|tender alerts?|bid database|bid alerts?|rfp database|rfq database|government contracts database|procurement platform|business directory|supplier directory|free template|proposal template|download template|resume template|blog article|how to guide|course|tutorial)/i;
const providerText=/(we provide engineering services|our engineering services|engineering consultants|design consultants|cad services|drafting services|software development company|our software development services|technology consulting services|custom software company|engineering design services|steel detailing services|fabrication drawing services)/i;
const buyerCompany={Engineering:/(manufacturer|manufacturing|oem|machine builder|machinery|industrial equipment|process equipment|packaging equipment|material handling|conveyor|fabricator|fabrication|machine shop|machining|cnc|plastics|injection molding|blow molding|food processing|steel products|metal products|production facility|plant|contractor)/i,Software:/(manufacturer|manufacturing|industrial|field service|contractor|distributor|logistics|warehouse|production|facility|business|company|operations)/i};
const projectRx={Engineering:/(plant expansion|facility expansion|new facility|new production line|capital investment|capital project|new equipment|new machinery|equipment development|equipment design|product development|custom equipment|manufacturing|fabrication|machining|material handling|process equipment|packaging equipment|automation)/i,Software:/(application modernization|legacy system|system replacement|implementation project|integration project|digital transformation|workflow automation|customer portal|crm implementation|enterprise application|system upgrade|cloud migration|business systems|production tracking|inventory|scheduling|field service|document control|quoting|estimating)/i};
const serviceRx={Engineering:/(mechanical|cad|draft|drawing|fabrication|plant|equipment|machine|structural|steel|inventor|solidworks|autocad|manufacturing|machining|conveyor|material handling|process equipment)/i,Software:/(software|application|system integration|workflow|automation|portal|crm|modernization|migration|digital transformation|dashboard|scheduling|inventory|production tracking|field service|document control|quoting|estimating)/i};
function decode(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function host(u:string){try{return new URL(u).hostname.replace(/^www\./,"").toLowerCase()}catch{return""}}
function brandFromHost(h:string){const first=h.split(".")[0].replace(/[-_]/g," ").trim();return first.length>=3?first.replace(/\b\w/g,c=>c.toUpperCase()):""}
function meta(html:string,rx:RegExp){const m=html.match(rx);return m?decode(m[1]):""}
function companyFromOfficialPage(html:string,url:string){const h=host(url),brand=brandFromHost(h);const og=meta(html,/<meta[^>]+property=["']og:site_name["'][^>]+content=["']([^"']+)["']/i)||meta(html,/<meta[^>]+content=["']([^"']+)["'][^>]+property=["']og:site_name["']/i);const app=meta(html,/<meta[^>]+name=["']application-name["'][^>]+content=["']([^"']+)["']/i);const candidates=[og,app,brand].map(x=>x.replace(/\s*[|–—].*$/," ").trim()).filter(x=>x.length>=3&&x.length<=80&&!invalidText.test(x)&&!serviceRx.Engineering.test(x)&&!serviceRx.Software.test(x));return candidates[0]||brand}
function service(d:Division,text:string){const t=text.toLowerCase();if(d==="Engineering"){if(/inventor|solidworks|autocad|cad|draft|drawing/.test(t))return"CAD / drawing overflow support";if(/fabricat|shop drawing|steel/.test(t))return"Fabrication drawings / engineering support";if(/equipment|machine|material handling|conveyor|process/.test(t))return"Equipment / machine design support";return"Mechanical engineering support"}if(/quot|estimat/.test(t))return"Quoting / estimating software";if(/document control|approval/.test(t))return"Document control / workflow automation";if(/production|inventory|dashboard/.test(t))return"Production / operations software";if(/field service|schedul/.test(t))return"Field service / scheduling software";if(/modern|legacy|migration/.test(t))return"Legacy modernization";return"Custom internal software / workflow automation"}
async function ddg(q:string){try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36",Accept:"text/html"},cache:"no-store"});if(!r.ok)return[];const html=await r.text(),blocks=html.split(/result__body/i).slice(1,13),out:{url:string;title:string;text:string}[]=[];for(const b of blocks){const a=b.match(/href="([^"]+)"[^>]*class="[^"]*result__a[^>]*>([\s\S]*?)<\/a>/i)||b.match(/class="[^"]*result__a[^>]*href="([^"]+)"[^>]*>([\s\S]*?)<\/a>/i);if(!a)continue;let url=decode(a[1]);try{const u=new URL(url,"https://duckduckgo.com"),x=u.searchParams.get("uddg");if(x)url=decodeURIComponent(x)}catch{}out.push({url,title:decode(a[2]),text:decode(b.slice(0,3000))})}return out}catch{return[]}}
function invalid(u:string,t:string){return blockedHosts.test(host(u))||invalidText.test(t)}
async function confirmResult(r:{url:string;title:string;text:string},d:Division){const summary=`${r.title} ${r.text}`;if(invalid(r.url,summary)||providerText.test(summary))return null;try{const res=await fetch(r.url,{headers:{"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124 Safari/537.36",Accept:"text/html,application/xhtml+xml"},redirect:"follow",cache:"no-store",signal:AbortSignal.timeout(8000)});if(!res.ok)return null;const ct=res.headers.get("content-type")||"";if(!ct.includes("text/html"))return null;const html=(await res.text()).slice(0,180000),body=decode(html),combined=`${summary} ${body.slice(0,30000)}`,finalUrl=res.url||r.url;if(invalid(finalUrl,combined)||providerText.test(body.slice(0,20000)))return null;if(!buyerCompany[d].test(combined)||!serviceRx[d].test(combined)||!projectRx[d].test(combined))return null;const h=host(finalUrl),company=companyFromOfficialPage(html,finalUrl);if(!company||company.length<3||invalidText.test(company))return null;const brand=brandFromHost(h).toLowerCase(),cn=company.toLowerCase();if(!body.toLowerCase().includes(cn)&&!r.title.toLowerCase().includes(cn)&&!cn.includes(brand))return null;return{company,url:finalUrl,text:combined.slice(0,6500)}}catch{return null}}
export async function searchBuyerIntent(d:Division){const queries=d==="Engineering"?engineeringNeeds:softwareNeeds,out:DiscoveryCandidateInput[]=[],seen=new Set<string>(),domains=new Set<string>();for(const q of queries){for(const r of await ddg(q)){if(!/^https?:/i.test(r.url)||seen.has(r.url))continue;seen.add(r.url);const c=await confirmResult(r,d);if(!c)continue;const h=host(c.url);if(domains.has(h))continue;domains.add(h);out.push({company:c.company,division:d,service:service(d,c.text),website:`https://${h}`,sourceName:`Verified client prospect — ${d}`,sourceUrl:c.url,evidence:`Verified operating-company source. ${c.company} appears to be a potential buyer of Arch ${d.toLowerCase()} services based on company operations and relevant project/workload evidence. ${c.text.slice(0,1800)}`});if(out.length>=20)break}if(out.length>=20)break}return out}
