import{crawlPage,CrawledPage}from"./keyless-crawler";
type Division="Engineering"|"Software";
const badEmail=/(noreply|no-reply|privacy|abuse|webmaster|careers|jobs|recruit|investor|media|press|support|help|legal|security|billing|customer.?service)/i;
const linkRx=/(contact|about|leadership|leaders|team|people|management|executive|engineering|technology|information|digital|operations|directory|staff|corporate|company|who-we-are|our-team|management-team|officers|governance)/i;
const engineeringRoles=["engineering manager","mechanical engineering manager","design engineering manager","director of engineering","engineering director","vice president engineering","vice president of engineering","vp engineering","chief engineer","plant manager","operations manager","director of operations","manufacturing engineering manager","project engineering manager","engineering lead","head of engineering","general manager"];
const softwareRoles=["chief information officer","chief technology officer","cio","cto","vp information technology","vice president of information technology","vice president technology","vp technology","director of information technology","it director","director of technology","director of applications","applications director","director of business systems","business systems director","director of digital transformation","digital transformation director","director of operations","enterprise applications director","information systems director","head of technology","head of information technology","head of digital","digital director"];
function roleList(d:Division){return d==="Engineering"?engineeringRoles:softwareRoles}
function domain(u:string){try{const p=new URL(u).hostname.replace(/^www\./,"").toLowerCase().split(".");return p.length>2?p.slice(-2).join("."):p.join(".")}catch{return""}}
function same(e:string,h:string){const d=e.split("@")[1]?.toLowerCase()||"";return!!d&&(d===h||d.endsWith(`.${h}`)||h.endsWith(`.${d}`))}
function norm(s:string){return s.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"")}
function identityMatches(name:string,email:string){const parts=name.toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z\s'-]/g," ").split(/\s+/).filter(Boolean);if(parts.length<2)return false;const first=norm(parts[0]),last=norm(parts[parts.length-1]),local=norm((email.split("@")[0]||"").split("+")[0]);if(first.length<2||last.length<2||local.length<3)return false;const patterns=new Set([first+last,first[0]+last,first+last[0],last+first,last+first[0]]);return patterns.has(local)||(local.includes(first)&&local.includes(last))}
function names(t:string):string[]{const match=t.match(/\b[A-Z][A-Za-zÀ-ÖØ-öø-ÿ'’-]{1,30}(?:\s+[A-Z][A-Za-zÀ-ÖØ-öø-ÿ.'’-]{1,30}){1,3}\b/g);const found:string[]=match?Array.from(match):[];return found.filter((n:string)=>{const w:string[]=n.split(/\s+/);return w.length>=2&&w.length<=4&&!w.some((x:string)=>/^(engineering|mechanical|director|manager|vice|president|chief|officer|technology|information|digital|operations|contact|about|team|corporate|company|leadership|services|solutions)$/i.test(x))})}
function roleMatches(t:string,d:Division){const low=t.toLowerCase(),out:{name:string;role:string;distance:number}[]=[];for(const r of roleList(d)){let from=0;while(from<low.length){const i=low.indexOf(r,from);if(i<0)break;const start=Math.max(0,i-420),end=Math.min(t.length,i+r.length+420);for(const n of names(t.slice(start,end))){const ni=low.indexOf(n.toLowerCase(),start),distance=ni<0?9999:Math.abs(ni-i);if(distance<=420)out.push({name:n,role:r,distance})}from=i+r.length}}return out.sort((a,b)=>a.distance-b.distance)}
function verifiedMatch(p:CrawledPage,d:Division,h:string){for(const ec of p.emailContexts){const email=ec.email.toLowerCase();if(!same(email,h)||badEmail.test(email))continue;for(const m of roleMatches(ec.context,d))if(identityMatches(m.name,email))return{contactName:m.name,contactEmail:email,role:m.role,sourceUrl:p.url,identityVerified:true}}return null}
function decode(v:string){return v.replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim()}
function searchSnippetMatch(text:string,d:Division,h:string,sourceUrl:string){const match=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi);const emails:string[]=match?Array.from(match):[];for(const raw of emails){const email=raw.toLowerCase();if(!same(email,h)||badEmail.test(email))continue;for(const m of roleMatches(text,d))if(identityMatches(m.name,email))return{contactName:m.name,contactEmail:email,role:m.role,sourceUrl,identityVerified:true,sourceType:"public-web-search"}}return null}
async function publicWebSearch(h:string,d:Division){const roleQuery=d==="Engineering"?'("director of engineering" OR "engineering manager" OR "chief engineer")':'("CIO" OR "CTO" OR "director of information technology" OR "director of technology")';const q=`site:${h} ${roleQuery} "@${h}"`;try{const r=await fetch(`https://html.duckduckgo.com/html/?q=${encodeURIComponent(q)}`,{headers:{"User-Agent":"Mozilla/5.0 (compatible; ArchLeadAI/1.0)",Accept:"text/html"},cache:"no-store"});if(!r.ok)return[];const html=await r.text();const blocks:string[]=html.split(/result__body/i).slice(1,9);const out:{url:string;text:string}[]=[];for(const b of blocks){const href=(b.match(/href="([^"]+)"[^>]*class="[^"]*result__a/i)||b.match(/class="[^"]*result__a[^>]*href="([^"]+)"/i))?.[1];const snippet=b.match(/result__snippet[^>]*>([\s\S]*?)<\/a>|result__snippet[^>]*>([\s\S]*?)<\/div>/i);const text=decode(`${snippet?.[1]||snippet?.[2]||""} ${b.slice(0,1800)}`);if(!href)continue;let url=decode(href);try{const u=new URL(url,"https://duckduckgo.com");const uddg=u.searchParams.get("uddg");if(uddg)url=decodeURIComponent(uddg)}catch{}out.push({url,text})}return out}catch{return[]}}
async function inspect(url:string,d:Division,h:string,seen:Set<string>){if(seen.has(url))return null;seen.add(url);const p=await crawlPage(url);if(!p)return null;return{page:p,hit:verifiedMatch(p,d,h)}}
export async function enrichPublicContact(website:string,division:Division){const root=await crawlPage(website);if(!root)return null;const h=domain(root.url),seen=new Set<string>([root.url]);const rootHit=verifiedMatch(root,division,h);if(rootHit)return rootHit;const priority=root.links.filter(x=>linkRx.test(x));const secondary=root.links.filter(x=>!linkRx.test(x));for(const l of [...priority.slice(0,35),...secondary.slice(0,8)]){const a=await inspect(l,division,h,seen);if(!a)continue;if(a.hit)return a.hit;for(const u of a.page.links.filter(x=>linkRx.test(x)).slice(0,8)){const b=await inspect(u,division,h,seen);if(b?.hit)return b.hit;if(seen.size>=45)break}if(seen.size>=45)break}const web=await publicWebSearch(h,division);for(const r of web){const snippetHit=searchSnippetMatch(r.text,division,h,r.url);if(snippetHit)return snippetHit;const page=await inspect(r.url,division,h,seen);if(page?.hit)return{...page.hit,sourceType:"public-web-result"}}return null}
