export type Division="Engineering"|"Software";
export type ProviderContact={contactName:string;contactEmail:string;role:string;sourceUrl:string;provider:string;confidence:number};
const bad=/(noreply|no-reply|privacy|abuse|webmaster|careers|jobs|recruit|investor|media|press|support|help|legal|security|billing|customer.?service)/i;
const engineering=/(engineering|mechanical|design|manufacturing|plant|operations|chief engineer|project engineer)/i;
const software=/(information technology|\bit\b|technology|digital|applications|business systems|information systems|cio|cto)/i;
function host(v:string){try{return new URL(v).hostname.replace(/^www\./,"").toLowerCase()}catch{return v.replace(/^https?:\/\//,"").split("/")[0].replace(/^www\./,"").toLowerCase()}}
function sameDomain(email:string,website:string){const e=(email.split("@")[1]||"").toLowerCase(),h=host(website);return!!e&&(e===h||e.endsWith(`.${h}`)||h.endsWith(`.${e}`))}
function relevant(title:string,d:Division){return d==="Engineering"?engineering.test(title):software.test(title)}
function cleanName(first?:string,last?:string,full?:string){return(full||`${first||""} ${last||""}`).trim().replace(/\s+/g," ")}
async function hunter(domain:string,d:Division,key:string):Promise<ProviderContact|null>{const r=await fetch(`https://api.hunter.io/v2/domain-search?domain=${encodeURIComponent(domain)}&limit=100&api_key=${encodeURIComponent(key)}`,{cache:"no-store"});if(!r.ok)return null;const j:any=await r.json();const emails=Array.isArray(j?.data?.emails)?j.data.emails:[];const candidates=emails.filter((x:any)=>x?.value&&x?.position&&relevant(String(x.position),d)&&!bad.test(String(x.value))&&sameDomain(String(x.value),domain)).sort((a:any,b:any)=>(Number(b.confidence)||0)-(Number(a.confidence)||0));for(const x of candidates){const name=cleanName(x.first_name,x.last_name);if(name.split(/\s+/).length<2)continue;return{contactName:name,contactEmail:String(x.value).toLowerCase(),role:String(x.position),sourceUrl:`https://${domain}`,provider:"Hunter",confidence:Number(x.confidence)||0}}return null}
async function apollo(domain:string,d:Division,key:string):Promise<ProviderContact|null>{const titles=d==="Engineering"?["engineering manager","director of engineering","chief engineer","mechanical engineering manager","plant manager","operations manager"]:["chief information officer","chief technology officer","it director","director of information technology","director of technology","director of applications","director of business systems"];const r=await fetch("https://api.apollo.io/api/v1/mixed_people/search",{method:"POST",headers:{"Content-Type":"application/json","X-Api-Key":key},body:JSON.stringify({q_organization_domains:domain,person_titles:titles,page:1,per_page:25}),cache:"no-store"});if(!r.ok)return null;const j:any=await r.json();const people=Array.isArray(j?.people)?j.people:[];for(const p of people){const email=String(p?.email||"").toLowerCase(),title=String(p?.title||"");const name=cleanName(undefined,undefined,p?.name);if(!email||bad.test(email)||!sameDomain(email,domain)||!relevant(title,d)||name.split(/\s+/).length<2)continue;return{contactName:name,contactEmail:email,role:title,sourceUrl:p?.linkedin_url||`https://${domain}`,provider:"Apollo",confidence:p?.email_status==="verified"?100:70}}return null}
export async function enrichFromProvider(website:string,division:Division):Promise<ProviderContact|null>{const domain=host(website);if(!domain)return null;const hunterKey=process.env.HUNTER_API_KEY?.trim();if(hunterKey){try{const c=await hunter(domain,division,hunterKey);if(c)return c}catch{}}const apolloKey=process.env.APOLLO_API_KEY?.trim();if(apolloKey){try{const c=await apollo(domain,division,apolloKey);if(c)return c}catch{}}return null}
export function configuredContactProviders(){return[process.env.HUNTER_API_KEY?"Hunter":null,process.env.APOLLO_API_KEY?"Apollo":null].filter(Boolean) as string[]}
