import{crawlPage,CrawledPage}from"./keyless-crawler";
type Division="Engineering"|"Software";
const badEmail=/(noreply|no-reply|privacy|abuse|webmaster|careers|jobs|recruit|investor|media|press|support|help|legal|security|billing|customer.?service)/i;
const linkRx=/(contact|about|leadership|leaders|team|people|management|executive|engineering|technology|information|digital|operations|directory|staff|corporate|company)/i;
const engineeringRoles:string[]=["engineering manager","mechanical engineering manager","design engineering manager","director of engineering","engineering director","vice president engineering","vp engineering","chief engineer","plant manager","operations manager","director of operations","manufacturing engineering manager","project engineering manager"];
const softwareRoles:string[]=["chief information officer","chief technology officer","cio","cto","vp information technology","vice president of information technology","vp technology","director of information technology","it director","director of technology","director of applications","applications director","director of business systems","business systems director","director of digital transformation","digital transformation director","director of operations","enterprise applications director","information systems director"];
function roleList(d:Division){return d==="Engineering"?engineeringRoles:softwareRoles}
function domain(u:string){try{const p=new URL(u).hostname.replace(/^www\./,"").toLowerCase().split(".");return p.length>2?p.slice(-2).join("."):p.join(".")}catch{return""}}
function same(e:string,h:string){const d=e.split("@")[1]?.toLowerCase()||"";return!!d&&(d===h||d.endsWith(`.${h}`)||h.endsWith(`.${d}`))}
function norm(s:string){return s.toLowerCase().replace(/[^a-z0-9]/g,"")}
function emailLocal(e:string){return(e.split("@")[0]||"").toLowerCase()}
function identityMatches(name:string,email:string){const parts=name.toLowerCase().replace(/[^a-z\s'-]/g," ").split(/\s+/).filter(Boolean);if(parts.length<2)return false;const first=norm(parts[0]),last=norm(parts[parts.length-1]),local=norm(emailLocal(email));if(first.length<2||last.length<2)return false;return local===first+last||local===first[0]+last||local===first+last[0]||local===last+first||local.includes(first)&&local.includes(last)||local.startsWith(first.slice(0,Math.min(4,first.length)))&&local.includes(last)}
function names(t:string){const found:string[]=t.match(/\b[A-Z][a-z]+(?:\s+[A-Z][a-z.'-]+){1,3}\b/g)??[];return found.filter(n=>{const w=n.split(/\s+/);return w.length>=2&&w.length<=4&&!w.some(x=>/^(engineering|mechanical|director|manager|vice|president|chief|officer|technology|information|digital|operations|contact|about|team|corporate)$/i.test(x))})}
function roleMatches(t:string,d:Division){const low=t.toLowerCase(),out:{name:string;role:string;index:number}[]=[];for(const r of roleList(d)){let from=0;while(from<low.length){const i=low.indexOf(r,from);if(i<0)break;const before=names(t.slice(Math.max(0,i-260),i)),after=names(t.slice(i+r.length,i+r.length+260));for(const n of [...before.slice(-2),...after.slice(0,2)])if(n)out.push({name:n,role:r,index:i});from=i+r.length}}return out}
function verifiedMatch(p:CrawledPage,d:Division,h:string){for(const ec of p.emailContexts){const email=ec.email.toLowerCase();if(!same(email,h)||badEmail.test(email))continue;for(const m of roleMatches(ec.context,d)){if(identityMatches(m.name,email))return{contactName:m.name,contactEmail:email,role:m.role,sourceUrl:p.url,identityVerified:true}}}return null}
export async function enrichPublicContact(website:string,division:Division){const root=await crawlPage(website);if(!root)return null;const h=domain(root.url),pages:CrawledPage[]=[root],seen=new Set<string>([root.url]);const rootHit=verifiedMatch(root,division,h);if(rootHit)return rootHit;for(const l of root.links.filter(x=>linkRx.test(x)).slice(0,30)){if(seen.has(l))continue;seen.add(l);const p=await crawlPage(l);if(!p)continue;pages.push(p);const hit=verifiedMatch(p,division,h);if(hit)return hit;if(pages.length>=32)break;for(const u of p.links.filter(x=>linkRx.test(x)).slice(0,6)){if(seen.has(u)||pages.length>=32)continue;seen.add(u);const q=await crawlPage(u);if(!q)continue;pages.push(q);const deep=verifiedMatch(q,division,h);if(deep)return deep}}return null}
