import{crawlPage}from"./keyless-crawler";
type Division="Engineering"|"Software";
const badEmail=/(noreply|no-reply|privacy|abuse|webmaster|careers|jobs|recruit|investor|media|press|support|help|legal|security|billing|customer.?service)/i;
const linkRx=/(contact|about|leadership|leaders|team|people|management|executive|engineering|technology|information|digital|operations|directory|staff)/i;
const engineeringRoles:string[]=["engineering manager","mechanical engineering manager","director of engineering","engineering director","vice president engineering","vp engineering","chief engineer","plant manager","operations manager","director of operations"];
const softwareRoles:string[]=["chief information officer","chief technology officer","cio","cto","vp information technology","vice president of information technology","vp technology","director of information technology","it director","director of technology","director of applications","applications director","director of business systems","business systems director","director of digital transformation","digital transformation director","director of operations"];
function roleList(d:Division):string[]{return d==="Engineering"?engineeringRoles:softwareRoles;}
function host(u:string){try{return new URL(u).hostname.replace(/^www\./,"").toLowerCase()}catch{return""}}
function same(e:string,h:string){const d=e.split("@")[1]?.toLowerCase()||"";return!!d&&(d===h||d.endsWith(`.${h}`)||h.endsWith(`.${d}`))}
function names(t:string):string[]{const found:string[]=t.match(/\b[A-Z][a-z]+(?:\s+[A-Z][a-z.'-]+){1,3}\b/g)??[];return found.filter((n:string)=>{const w:string[]=n.split(/\s+/);return w.length>=2&&w.length<=4&&!w.some((x:string)=>/^(engineering|mechanical|director|manager|vice|president|chief|officer|technology|information|digital|operations|contact|about|team)$/i.test(x));});}
function matchedName(t:string,d:Division){const low=t.toLowerCase();for(const r of roleList(d)){const i=low.indexOf(r);if(i<0)continue;const before:string[]=names(t.slice(Math.max(0,i-260),i));const after:string[]=names(t.slice(i+r.length,i+r.length+260));const n:string|undefined=before.length?before[before.length-1]:after[0];if(n)return{name:n,role:r};}return null;}
export async function enrichPublicContact(website:string,division:Division){const root=await crawlPage(website);if(!root)return null;const h=host(root.url),pages=[root],seen=new Set<string>([root.url]);for(const l of root.links.filter(x=>linkRx.test(x)).slice(0,24)){if(seen.has(l))continue;seen.add(l);const p=await crawlPage(l);if(!p)continue;pages.push(p);for(const d of p.links.filter(x=>linkRx.test(x)).slice(0,8)){if(seen.has(d)||pages.length>=36)continue;seen.add(d);const q=await crawlPage(d);if(q)pages.push(q);}}for(const p of pages){for(const ec of p.emailContexts){const email:string=ec.email.toLowerCase();if(!same(email,h)||badEmail.test(email))continue;const m=matchedName(ec.context,division);if(m)return{contactName:m.name,contactEmail:email,role:m.role,sourceUrl:p.url};}}return null;}
