export type Division="Engineering"|"Software";
export type ProspectType="Client Prospect"|"Partner Prospect"|"Competitor"|"Invalid"|"Research More";
export type DiscoveryCandidateInput={company:string;division:Division;service?:string;website?:string;contactName?:string;contactEmail?:string;sourceName?:string;sourceUrl?:string;evidence?:string;};
export type ScoredCandidate=DiscoveryCandidateInput&{score:number;decision:"Qualified"|"Review"|"Rejected";reason:string;};
const engineeringFit=["inventor","solidworks","autocad","cad","mechanical design","shop drawing","fabrication drawing","manufacturing drawing","assembly drawing","bom","equipment design","machine design","custom equipment","custom machinery","material handling","engineering automation","ilogic","manufacturing engineering","industrial equipment","structural steel","welding","fabrication","machining","cnc","process equipment","conveyor","tank","hopper","platform","support structure"];
const softwareFit=["custom software","internal application","internal tool","workflow automation","business process","web application","web app","mobile application","mobile app","crm","customer portal","client portal","employee portal","tenant portal","api integration","system integration","quickbooks","dashboard","field service","scheduling","dispatch","work order","legacy system","modernization","digital transformation","business systems","inventory","production tracking","quality tracking","inspection","estimating","quoting","document control","approval workflow","online ordering","ecommerce","website redesign","spreadsheet","excel","paper form","manual data entry","payment integration"];
const engineeringBuyerTypes=["manufacturer","manufacturing","oem","fabricator","fabrication","machine builder","machine shop","machining","industrial equipment","process equipment","packaging equipment","material handling","conveyor","plastics","injection molding","blow molding","food equipment","food processing","construction","contractor","mechanical contractor","production facility","steel products","metal products","custom machinery","equipment manufacturer"];
const softwareBuyerTypes=[...engineeringBuyerTypes,"field service","hvac","plumbing","electrical contractor","landscaping","cleaning service","property management","distributor","distribution","logistics","warehouse","retail","restaurant","professional services","service company","operations"];
const opportunitySignals=["rfp","rfq","request for proposal","request for quote","seeking vendor","seeking contractor","requesting proposals","outsourc","subcontract","overflow","additional engineering capacity","hiring","job opening","engineering opening","designer opening","drafter opening","new facility","new production line","plant expansion","facility expansion","capacity expansion","capital investment","capital project","project award","awarded project","new product","product development","equipment development","new equipment","new machinery","increased production","production capacity","automation project","system replacement","legacy system","implementation project","integration project","digital transformation","manual process","manual data entry","paper form","spreadsheet","excel","quoting","estimating","production tracking","field service","scheduling","dispatch","work order","inventory","document control","customer portal","online ordering","ecommerce","website redesign","quickbooks","api integration","dashboard","new location","expansion"];
const providerSignals=["engineering consulting","engineering consultants","cad services","drafting services","steel detailing services","shop drawing services","engineering outsourcing","professional engineering services","pe stamping services","software development company","software development services","technology consulting services","custom software company","web design agency","digital agency","app development company"];
const partnerSignals=["seeking subcontractor","subcontract engineering","engineering partner","overflow partner","external engineering support","staff augmentation","contract engineer","contract designer"];
const invalidSignals=["tender portal","tender alerts","bid database","bid alerts","business directory","supplier directory","industrial directory","industrial marketplace","job board","free template","proposal template","tutorial","course","resume","how to write","blog article"];
const regionalSignals=["st. louis","saint louis","missouri","kansas city","illinois","kansas","arkansas","iowa","nebraska","tennessee","midwest"];
function hits(text:string,terms:string[]){return terms.filter(x=>text.includes(x));}
function classify(text:string,buyerTypes:string[]){if(hits(text,invalidSignals).length)return"Invalid" as ProspectType;const provider=hits(text,providerSignals).length>0,partner=hits(text,partnerSignals).length>0;if(provider&&partner)return"Partner Prospect" as ProspectType;if(provider)return"Competitor" as ProspectType;if(hits(text,buyerTypes).length)return"Client Prospect" as ProspectType;return"Research More" as ProspectType;}
export function scoreCandidate(input:DiscoveryCandidateInput):ScoredCandidate{const text=`${input.company} ${input.service??""} ${input.evidence??""} ${input.sourceName??""} ${input.sourceUrl??""} ${input.website??""}`.toLowerCase();const buyerTypes=input.division==="Engineering"?engineeringBuyerTypes:softwareBuyerTypes,type=classify(text,buyerTypes),fitHits=hits(text,input.division==="Engineering"?engineeringFit:softwareFit),oppHits=hits(text,opportunitySignals),buyerHits=hits(text,buyerTypes),regional=hits(text,regionalSignals);
let serviceFit=0;if(fitHits.length>=4)serviceFit=3;else if(fitHits.length>=2)serviceFit=2;else if(fitHits.length>=1)serviceFit=1;else if(type==="Client Prospect"&&buyerHits.length>=2)serviceFit=1;
let opportunity=0;if(oppHits.length>=2)opportunity=2;else if(oppHits.length===1)opportunity=1;else if(type==="Client Prospect"&&serviceFit>=2)opportunity=1;
const strategic=regional.length?1:0;const preScore=serviceFit+opportunity+strategic;const normalized=Math.round(preScore/6*100);
let decision:ScoredCandidate["decision"]="Review";if(type==="Invalid"||type==="Competitor")decision="Rejected";else if(type==="Partner Prospect")decision=preScore>=3?"Qualified":"Review";else if(type==="Client Prospect"){const provenBuyerFit=buyerHits.length>=1&&serviceFit>=2;const activeTrigger=oppHits.length>=1&&serviceFit>=1;decision=(preScore>=4||provenBuyerFit||activeTrigger)?"Qualified":preScore>=2?"Review":"Rejected"}else decision=preScore>=4?"Qualified":"Review";
const reason=`${decision}: ${type}. Pre-contact score ${preScore}/6 (service fit ${serviceFit}/3, opportunity evidence ${opportunity}/2, strategic value ${strategic}/1).${fitHits.length?` Arch-fit evidence: ${fitHits.slice(0,5).join(", ")}.`:""}${oppHits.length?` Opportunity signals: ${oppHits.slice(0,4).join(", ")}.`:""}${type==="Client Prospect"&&!oppHits.length&&serviceFit>=2?" Strong operating-company/service fit retained even without a public RFP; Arch can be positioned as overflow/project capacity.":""}${type==="Research More"?" Company may still be useful; research further rather than treating missing public evidence as a hard rejection.":""}`;return{...input,score:normalized,decision,reason};}
export function validateCandidate(value:unknown):DiscoveryCandidateInput|null{if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>;if(typeof v.company!=="string"||!v.company.trim())return null;if(v.division!=="Engineering"&&v.division!=="Software")return null;const str=(k:string)=>typeof v[k]==="string"?String(v[k]).trim()||undefined:undefined;return{company:v.company.trim(),division:v.division,service:str("service"),website:str("website"),contactName:str("contactName"),contactEmail:str("contactEmail")?.toLowerCase(),sourceName:str("sourceName"),sourceUrl:str("sourceUrl"),evidence:str("evidence")};}
