export type Division = "Engineering" | "Software";
export type DiscoveryCandidateInput={company:string;division:Division;service?:string;website?:string;contactName?:string;contactEmail?:string;sourceName?:string;sourceUrl?:string;evidence?:string;};
export type ScoredCandidate=DiscoveryCandidateInput&{score:number;decision:"Qualified"|"Review"|"Rejected";reason:string;};
const engineeringSignals=["autodesk inventor","inventor","solidworks","autocad","cad designer","cad drafter","mechanical drafter","mechanical design engineer","mechanical design","shop drawing","fabrication drawing","manufacturing drawing","bom","reverse engineering","steel detailing","plant engineering","product design","equipment design","machine design","cad automation","ilogic","manufacturing engineering","industrial equipment","new product development"];
const softwareSignals=["custom software","internal application","workflow automation","business process automation","web application","mobile application","mobile app","crm","customer portal","api integration","system integration","dashboard","field service","scheduling system","legacy system","modernization","digital transformation","enterprise application","business systems","software platform"];
const strongBuyerSignals=["rfp","rfq","request for proposal","request for quote","invitation to bid","solicitation","seeking vendor","seeking contractor","looking for vendor","looking for contractor","implementation partner","requesting proposals","accepting proposals","bid opportunity","vendor opportunity","supplier opportunity","procurement opportunity","outsource","outsourcing","subcontract","subcontractor","contract engineer","contract designer","temporary engineering support","staff augmentation"];
const projectSignals=["new system","system replacement","replace legacy","application modernization","modernization project","implementation project","integration project","migration project","digital transformation initiative","new facility","new production line","plant expansion","capacity expansion","capital project","engineering backlog","design support needed","engineering support needed","drafting support needed","overflow support","additional engineering capacity","external engineering support","facility expansion","product development","equipment development","manufacturing project","automation project","system upgrade","platform upgrade"];
const careerSignals=["careers","career","job opportunities","job opening","jobs","hiring","apprenticeship","students and veterans","students and new grads","apply now","employment opportunity"];
const providerSignals=["we provide engineering services","we provide cad services","our cad services","our drafting services","engineering services company","engineering consultants","design consultants","software development company","we build custom software","our software development services","technology consulting services","our engineering services","our software services"];
const directorySignals=["bid database","bid alerts","search bids","tender alerts","directory","job board","free template","sample rfp","how to write","tutorial","course","resume","student"];
function hits(text:string,terms:string[]){return terms.filter(term=>text.includes(term));}
function sourceLooksCareer(input:DiscoveryCandidateInput,text:string){return /career|job|employment|apprentice|student/i.test(`${input.sourceName??""} ${input.sourceUrl??""}`)||hits(text,careerSignals).length>=2;}
export function scoreCandidate(input:DiscoveryCandidateInput):ScoredCandidate{const text=`${input.company} ${input.service??""} ${input.evidence??""} ${input.sourceName??""} ${input.sourceUrl??""}`.toLowerCase(),serviceHits=hits(text,input.division==="Engineering"?engineeringSignals:softwareSignals),buyer=hits(text,strongBuyerSignals),project=hits(text,projectSignals),career=hits(text,careerSignals),provider=hits(text,providerSignals),directory=hits(text,directorySignals),careerPage=sourceLooksCareer(input,text);const explicitBuyer=buyer.length>0,strongFit=serviceHits.length>=2&&(project.length>=1||serviceHits.length>=3),providerOnly=provider.length>0&&!explicitBuyer&&project.length===0,badSource=directory.length>0&&!explicitBuyer;let score=12+Math.min(36,serviceHits.length*9)+Math.min(42,buyer.length*18)+Math.min(30,project.length*12);if(input.website)score+=3;if(input.sourceUrl)score+=3;if(input.contactEmail)score+=2;if(serviceHits.length===0)score-=30;if(careerPage&&!explicitBuyer)score-=30;if(providerOnly)score-=45;if(badSource)score-=40;score-=Math.min(24,career.length*8);score=Math.max(0,Math.min(100,score));let decision:ScoredCandidate["decision"];let classification="";if(providerOnly||badSource||serviceHits.length===0){decision="Rejected";classification=providerOnly?"service provider/competitor evidence without a client-side project":badSource?"directory/aggregator content is not a prospect":"no meaningful Arch service fit detected";}else if(explicitBuyer&&serviceHits.length>0){decision=score>=65?"Qualified":"Review";classification="A — active buyer opportunity";}else if(strongFit&&!careerPage){decision=score>=55?"Qualified":"Review";classification="B — strong-fit prospect with relevant work/project evidence";}else{decision=score>=40?"Review":"Rejected";classification="C — possible prospect; evidence is not strong enough for automatic outreach";}const positives=[...serviceHits.slice(0,3),...buyer.slice(0,2),...project.slice(0,2)];const reason=`${decision}: ${classification}${positives.length?`; matched ${positives.join(", ")}`:""}${input.contactEmail?"; public email observed but contact verification remains a separate gate":""}.`;return{...input,score,decision,reason};}
export function validateCandidate(value:unknown):DiscoveryCandidateInput|null{if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>;if(typeof v.company!=="string"||!v.company.trim())return null;if(v.division!=="Engineering"&&v.division!=="Software")return null;const str=(key:string)=>typeof v[key]==="string"?String(v[key]).trim()||undefined:undefined;return{company:v.company.trim(),division:v.division,service:str("service"),website:str("website"),contactName:str("contactName"),contactEmail:str("contactEmail")?.toLowerCase(),sourceName:str("sourceName"),sourceUrl:str("sourceUrl"),evidence:str("evidence")};}
