export type Division = "Engineering" | "Software";
export type DiscoveryCandidateInput={company:string;division:Division;service?:string;website?:string;contactName?:string;contactEmail?:string;sourceName?:string;sourceUrl?:string;evidence?:string;};
export type ScoredCandidate=DiscoveryCandidateInput&{score:number;decision:"Qualified"|"Review"|"Rejected";reason:string;};
const engineeringSignals=["autodesk inventor","inventor","solidworks","autocad","cad designer","cad drafter","mechanical drafter","mechanical design engineer","mechanical design","shop drawing","fabrication drawing","manufacturing drawing","bom","reverse engineering","steel detailing","plant engineering","product design","equipment design","machine design","cad automation","ilogic"];
const softwareSignals=["custom software","internal application","workflow automation","business process automation","web application","mobile application","mobile app","crm","customer portal","api integration","system integration","dashboard","field service","scheduling system","legacy system","modernization","digital transformation"];
const strongBuyerSignals=["rfp","rfq","request for proposal","request for quote","invitation to bid","solicitation","seeking vendor","seeking contractor","looking for vendor","looking for contractor","implementation partner","requesting proposals","accepting proposals","bid opportunity","vendor opportunity","supplier opportunity","procurement opportunity","outsource","outsourcing","subcontract","subcontractor","contract engineer","contract designer","temporary engineering support","staff augmentation"];
const projectBuyerSignals=["new system","system replacement","replace legacy","application modernization","modernization project","implementation project","integration project","migration project","digital transformation initiative","new facility","new production line","plant expansion","capacity expansion","capital project","engineering backlog","design support needed","engineering support needed","drafting support needed","overflow support","additional engineering capacity","external engineering support"];
const careerSignals=["careers","career","job opportunities","job opening","jobs","hiring","apprenticeship","students and veterans","students and new grads","apply now","employment opportunity"];
const productSignals=["products & services","products and services","our products","product support","product training","industries","solutions","measurement","instrumentation","automation platform","processor cards","software & drivers","services & support"];
const providerSignals=["we provide engineering services","we provide cad services","our cad services","our drafting services","engineering services company","software development company","we build custom software","our software development services","technology consulting services"];
const negativeSignals=["student","tutorial","course","job seeker","resume","free template","personal project","lorem ipsum"];
function hits(text:string,terms:string[]){return terms.filter(term=>text.includes(term));}
function sourceLooksCareer(input:DiscoveryCandidateInput,text:string){return /career|job|employment|apprentice|student/i.test(`${input.sourceName??""} ${input.sourceUrl??""}`)||hits(text,careerSignals).length>=2;}
export function scoreCandidate(input:DiscoveryCandidateInput):ScoredCandidate{const text=`${input.service??""} ${input.evidence??""} ${input.sourceName??""} ${input.sourceUrl??""}`.toLowerCase(),serviceHits=hits(text,input.division==="Engineering"?engineeringSignals:softwareSignals),strong=hits(text,strongBuyerSignals),project=hits(text,projectBuyerSignals),career=hits(text,careerSignals),product=hits(text,productSignals),negative=hits(text,negativeSignals),provider=hits(text,providerSignals),careerPage=sourceLooksCareer(input,text);let score=8+Math.min(24,serviceHits.length*6)+Math.min(48,strong.length*18)+Math.min(30,project.length*12);if(input.website)score+=2;if(input.sourceUrl)score+=2;if(input.contactEmail)score+=2;if(strong.length===0&&project.length===0)score-=28;if(careerPage&&strong.length===0)score-=22;score-=Math.min(30,career.length*6);score-=Math.min(28,product.length*5);score-=Math.min(40,negative.length*15);score-=Math.min(35,provider.length*18);score=Math.max(0,Math.min(100,score));const buyerConfirmed=strong.length>0||project.length>=2;let decision:ScoredCandidate["decision"]=buyerConfirmed&&score>=70?"Qualified":score>=45?"Review":"Rejected";if(careerPage&&strong.length===0)decision=score>=45?"Review":"Rejected";if(!buyerConfirmed&&decision==="Qualified")decision="Review";const positives=[...serviceHits.slice(0,2),...strong.slice(0,2),...project.slice(0,2)];const blockers=[] as string[];if(!buyerConfirmed)blockers.push("buyer demand not confirmed");if(careerPage&&strong.length===0)blockers.push("career/hiring content is not treated as purchase intent");if(product.length&&strong.length===0&&project.length<2)blockers.push("company product/capability content is not treated as purchase intent");const reason=positives.length?`${decision}: matched ${positives.join(", ")}; ${buyerConfirmed?"credible buyer/project intent detected":blockers.join("; ")||"buyer intent not sufficiently confirmed"}${input.contactEmail?"; public email observed but not used as buyer-intent evidence":""}.`:`${decision}: insufficient buyer/service evidence for automatic qualification${blockers.length?`; ${blockers.join("; ")}`:""}.`;return{...input,score,decision,reason};}
export function validateCandidate(value:unknown):DiscoveryCandidateInput|null{if(!value||typeof value!=="object")return null;const v=value as Record<string,unknown>;if(typeof v.company!=="string"||!v.company.trim())return null;if(v.division!=="Engineering"&&v.division!=="Software")return null;const str=(key:string)=>typeof v[key]==="string"?String(v[key]).trim()||undefined:undefined;return{company:v.company.trim(),division:v.division,service:str("service"),website:str("website"),contactName:str("contactName"),contactEmail:str("contactEmail")?.toLowerCase(),sourceName:str("sourceName"),sourceUrl:str("sourceUrl"),evidence:str("evidence")};}
