import{getCloudflareContext}from"@opennextjs/cloudflare";
type GmailEnv=CloudflareEnv&{GOOGLE_CLIENT_ID?:string;GOOGLE_CLIENT_SECRET?:string;GOOGLE_REFRESH_TOKEN?:string};
function env(){return getCloudflareContext().env as GmailEnv}
function b64url(v:string){const bytes=new TextEncoder().encode(v);let s="";for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
async function token(){const e=env();if(!e.GOOGLE_CLIENT_ID||!e.GOOGLE_CLIENT_SECRET||!e.GOOGLE_REFRESH_TOKEN)throw new Error("Gmail OAuth is not configured. Add GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET and GOOGLE_REFRESH_TOKEN as Cloudflare secrets.");const body=new URLSearchParams({client_id:e.GOOGLE_CLIENT_ID,client_secret:e.GOOGLE_CLIENT_SECRET,refresh_token:e.GOOGLE_REFRESH_TOKEN,grant_type:"refresh_token"});const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body});const j:any=await r.json();if(!r.ok||!j.access_token)throw new Error(`Gmail OAuth token failed (${r.status}).`);return String(j.access_token)}
async function api(path:string,t:string,init?:RequestInit){const r=await fetch(`https://gmail.googleapis.com/gmail/v1/users/me${path}`,{...init,headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json",...(init?.headers||{})}});const j:any=await r.json().catch(()=>({}));if(!r.ok)throw new Error(`Gmail API failed (${r.status}): ${j?.error?.message||"request failed"}`);return j}
async function label(t:string,name:string){const list=await api("/labels",t);const found=(list.labels||[]).find((x:any)=>String(x.name).toLowerCase()===name.toLowerCase());if(found?.id)return String(found.id);const made=await api("/labels",t,{method:"POST",body:JSON.stringify({name,labelListVisibility:"labelShow",messageListVisibility:"show"})});return String(made.id)}
export function gmailConfigured(){const e=env();return Boolean(e.GOOGLE_CLIENT_ID&&e.GOOGLE_CLIENT_SECRET&&e.GOOGLE_REFRESH_TOKEN)}
export async function sendGmailMessage(x:{sender:string;recipient:string;subject:string;body:string;division:"Engineering"|"Software"}){const t=await token();const raw=[`From: Sridhar Kota <${x.sender}>`,`To: ${x.recipient}`,`Subject: ${x.subject}`,"MIME-Version: 1.0","Content-Type: text/plain; charset=UTF-8","Content-Transfer-Encoding: 8bit","",x.body].join("\r\n");const sent=await api("/messages/send",t,{method:"POST",body:JSON.stringify({raw:b64url(raw)})});const labelId=await label(t,x.division);await api(`/messages/${encodeURIComponent(sent.id)}/modify`,t,{method:"POST",body:JSON.stringify({addLabelIds:[labelId]})});return{messageId:String(sent.id),threadId:String(sent.threadId||""),label:x.division}}
