export type EmailContext={email:string;context:string};
export type CrawledPage={url:string;title:string;text:string;links:string[];emails:string[];emailContexts:EmailContext[]};
function decodeHtml(value:string){return value.replace(/&nbsp;/gi," ").replace(/&amp;/gi,"&").replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/&lt;/gi,"<").replace(/&gt;/gi,">");}
function stripHtml(html:string){return decodeHtml(html.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim());}
function titleOf(html:string){const m=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?stripHtml(m[1]).slice(0,180):"";}
function emailDataOf(html:string){const decoded=decodeHtml(html),emails=new Set<string>(),contexts=new Map<string,string>();const add=(email:string,index:number)=>{const clean=email.trim().toLowerCase();if(!clean)return;emails.add(clean);if(!contexts.has(clean)){const start=Math.max(0,index-900),end=Math.min(decoded.length,index+900);contexts.set(clean,stripHtml(decoded.slice(start,end)).slice(0,1800));}};const mailto=/href=["']mailto:([^"'?#\s>]+)/gi;let m:RegExpExecArray|null;while((m=mailto.exec(decoded)))add(m[1],m.index);const visible=/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi;while((m=visible.exec(decoded)))add(m[0],m.index);return{emails:[...emails].slice(0,75),emailContexts:[...contexts.entries()].slice(0,75).map(([email,context])=>({email,context}))};}
const careerHosts=["myworkdayjobs.com","workday.com","greenhouse.io","lever.co","icims.com","smartrecruiters.com","jobvite.com","successfactors.com","oraclecloud.com"];
function rootDomain(host:string){const p=host.toLowerCase().replace(/^www\./,"").split(".").filter(Boolean);return p.length<=2?p.join("."):p.slice(-2).join(".");}
function trustedExternal(host:string){return careerHosts.some(x=>host===x||host.endsWith(`.${x}`));}
function linksOf(html:string,base:string){const out=new Set<string>(),baseHost=new URL(base).hostname,baseRoot=rootDomain(baseHost);const re=/href=["']([^"'#]+)["']/gi;let m:RegExpExecArray|null;while((m=re.exec(html))){try{const u=new URL(m[1],base);if(u.protocol!=="http:"&&u.protocol!=="https:")continue;const sameCompany=rootDomain(u.hostname)===baseRoot;if(!sameCompany&&!trustedExternal(u.hostname))continue;out.add(u.toString());}catch{}}return [...out].slice(0,180);}
export async function crawlPage(url:string):Promise<CrawledPage|null>{try{const res=await fetch(url,{headers:{"User-Agent":"ArchLeadAI/1.0 (+https://archengineeringservices.com)",Accept:"text/html,application/xhtml+xml"},redirect:"follow",cache:"no-store"});if(!res.ok)return null;const type=res.headers.get("content-type")||"";if(!type.includes("text/html")&&!type.includes("application/xhtml+xml"))return null;const html=(await res.text()).slice(0,750000),emailData=emailDataOf(html);return{url:res.url,title:titleOf(html),text:stripHtml(html).slice(0,40000),links:linksOf(html,res.url),emails:emailData.emails,emailContexts:emailData.emailContexts};}catch{return null;}}
export function parseSeedList(value:string|undefined|null){if(!value)return[];return value.split(/[\n,]+/).map(x=>x.trim()).filter(Boolean).filter(x=>{try{const u=new URL(x);return u.protocol==="https:"||u.protocol==="http:"}catch{return false}}).slice(0,25);}
