import type {DiscoveryCandidateInput} from "./discovery";
import {crawlPage} from "./keyless-crawler";

const needs=[
 ["Autodesk Inventor / CAD support",["autodesk inventor","inventor designer","cad designer","cad drafter","mechanical drafter","autocad"]],
 ["SolidWorks / mechanical design support",["solidworks","mechanical design","mechanical designer","mechanical design engineer","product design engineer"]],
 ["Fabrication / shop drawings",["fabrication drawing","shop drawing","fabrication drawings","detail drawing","production drawing","manufacturing drawing","assembly drawing","weldment drawing"]],
 ["Equipment / machine design",["equipment design","machine design","industrial equipment","custom equipment","custom machinery","material handling"]],
 ["Plant / structural engineering support",["plant expansion","new production line","new facility","structural support","platform design","steel structure"]],
 ["CAD automation / drawing productivity",["cad automation","design automation","drawing automation","bom automation","engineering automation","ilogic"]],
 ["Engineering overflow / staffing demand",["engineering backlog","urgent hiring","multiple openings","mechanical engineer","mechanical design engineer","cad designer","mechanical drafter","contract engineer","contract designer"]],
] as const;
const buyer=["rfp","rfq","request for proposal","request for quote","seeking","looking for","contractor","consultant","vendor","project","expansion","new facility","new production line","hiring","opening","job","career","backlog","design support"];
const provider=["we provide","our services","engineering services company","cad services","drafting services","contact us for","we specialize in"];
const follow=/(career|jobs?|myworkdayjobs|workday|greenhouse|lever|icims|smartrecruiters|jobvite|successfactors|oraclecloud|news|press|project|expansion|rfp|rfq|bid|solicitation|procurement|engineering|design)/i;
const contactFollow=/(contact|about|leadership|team|management|engineering)/i;
const roleTerms:string[]=["engineering manager","mechanical engineering manager","design engineering manager","director of engineering","engineering director","plant manager","operations manager","manufacturing engineering manager","project engineering manager","chief engineer","vp engineering","vice president engineering"];
function matched(text:string,terms:readonly string[]){return terms.filter(x=>text.includes(x));}
function company(url:string,fallback:string){try{const h=new URL(url).hostname.replace(/^www\./,"");if(/(workday|myworkdayjobs|greenhouse|lever|icims|smartrecruiters|jobvite|successfactors|oraclecloud)/i.test(h))return fallback;return h}catch{return fallback}}
function publicEmail(text:string,host:string){const emails:string[]=text.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/gi)??[];const domain=host.replace(/^www\./,"").toLowerCase();return emails.map((x:string)=>x.toLowerCase()).find((x:string)=>x.endsWith(`@${domain}`)&&!/(noreply|no-reply|privacy|abuse|webmaster)/.test(x));}
function contactName(text:string){const lower=text.toLowerCase();for(const role of roleTerms){const i=lower.indexOf(role);if(i<0)continue;const around=text.slice(Math.max(0,i-100),Math.min(text.length,i+role.length+100));const names:string[]=around.match(/\b[A-Z][a-z]+(?:\s+[A-Z][a-z.'-]+){1,2}\b/g)??[];const n=names.find((x:string)=>!roleTerms.some((r:string)=>r.includes(x.toLowerCase())));if(n)return n;}return undefined;}
async function discoverContact(rootUrl:string){const root=await crawlPage(rootUrl);if(!root)return{};const host=new URL(root.url).hostname;const pages=[root];for(const link of root.links.filter(x=>contactFollow.test(x)).slice(0,6)){const p=await crawlPage(link);if(p)pages.push(p);}for(const p of pages){const email=publicEmail(p.text,host),name=contactName(p.text);if(email||name)return{contactEmail:email,contactName:name};}return{};}
function evaluate(url:string,title:string,text:string,sourceName:string,sourceCompany:string):DiscoveryCandidateInput|null{const t=`${title} ${text}`.toLowerCase();let best:{name:string;hits:string[]}|null=null;for(const [name,terms] of needs){const h=matched(t,terms);if(h.length&&(!best||h.length>best.hits.length))best={name,hits:h};}if(!best)return null;const buyerHits=matched(t,buyer),providerHits=matched(t,provider);if(providerHits.length>=2&&buyerHits.length===0)return null;const co=company(url,sourceCompany);const evidence=`${title||co}. Need detected: ${best.name}. Evidence terms: ${best.hits.slice(0,6).join(", ")}${buyerHits.length?`. Buyer intent: ${buyerHits.slice(0,5).join(", ")}`:""}. ${text.slice(0,1200)}`;return{company:co,division:"Engineering",service:best.name,website:(()=>{try{return new URL(sourceCompany.startsWith("http")?sourceCompany:url).origin}catch{return undefined}})(),sourceName,sourceUrl:url,evidence};}
export async function searchMechanicalLeads(sources:{name:string;url:string;source_type:string}[]){const out:DiscoveryCandidateInput[]=[],seen=new Set<string>(),candidateKeys=new Set<string>();for(const source of sources.slice(0,30)){const root=await crawlPage(source.url);if(!root)continue;const queue=root.links.filter(x=>follow.test(x)).slice(0,12);const pages=[root];for(const link of queue){if(seen.has(link))continue;seen.add(link);const p=await crawlPage(link);if(!p)continue;pages.push(p);for(const deep of p.links.filter(x=>follow.test(x)).slice(0,12)){if(seen.has(deep))continue;seen.add(deep);const d=await crawlPage(deep);if(d)pages.push(d);if(pages.length>=30)break;}if(pages.length>=30)break;}let contact:Partial<DiscoveryCandidateInput>|null=null;for(const p of pages){const key=p.url;if(seen.has(`eval:${key}`))continue;seen.add(`eval:${key}`);const c=evaluate(p.url,p.title,p.text,`Mechanical v3 — ${source.name}`,source.name);if(!c)continue;const candidateKey=`${c.company.trim().toLowerCase()}|${(c.service||"").trim().toLowerCase()}`;if(candidateKeys.has(candidateKey))continue;candidateKeys.add(candidateKey);if(contact===null)contact=source.source_type==="Company Website/Careers"?await discoverContact(source.url):{};out.push({...c,...contact});}}return out.slice(0,100);}
