import type {DiscoveryCandidateInput} from "./discovery";
import {crawlPage} from "./keyless-crawler";import{searchBuyerIntent}from"./buyer-intent-search";
const needs=[["Autodesk Inventor / CAD support",["autodesk inventor","inventor designer","cad designer","cad drafter","mechanical drafter","autocad"]],["SolidWorks / mechanical design support",["solidworks","mechanical design","mechanical designer","mechanical design engineer","product design engineer"]],["Fabrication / shop drawings",["fabrication drawing","shop drawing","fabrication drawings","detail drawing","production drawing","manufacturing drawing","assembly drawing","weldment drawing"]],["Equipment / machine design",["equipment design","machine design","industrial equipment","custom equipment","custom machinery","material handling"]],["Plant / structural engineering support",["plant expansion","new production line","new facility","structural support","platform design","steel structure"]],["CAD automation / drawing productivity",["cad automation","design automation","drawing automation","bom automation","engineering automation","ilogic"]],["Engineering capacity support",["engineering backlog","contract engineer","contract designer","temporary engineering support","staff augmentation","overflow support","external engineering support"]]]as const;
const strongBuyer=["rfp","rfq","request for proposal","request for quote","invitation to bid","solicitation","seeking vendor","seeking contractor","looking for vendor","looking for contractor","requesting proposals","accepting proposals","bid opportunity","vendor opportunity","supplier opportunity","procurement opportunity","outsource","outsourcing","subcontract","subcontractor","contract engineer","contract designer","temporary engineering support","staff augmentation"];
const projectBuyer=["new facility","new production line","plant expansion","facility expansion","capacity expansion","capital project","product development","new product development","equipment development","equipment design","manufacturing project","engineering backlog","design support needed","engineering support needed","drafting support needed","overflow support","additional engineering capacity","external engineering support"];
const provider=/(we provide engineering services|our engineering services|engineering consultants|design consultants|cad services company|drafting services company)/i;
const follow=/(project|expansion|news|press|innovation|product|equipment|manufacturing|rfp|rfq|bid|solicitation|procurement|supplier|vendor|contract|subcontract|engineering|design|capital|facility|production)/i;function matched(t:string,a:readonly string[]){return a.filter(x=>t.includes(x))}function company(u:string,f:string){try{return f||new URL(u).hostname.replace(/^www\./,"")}catch{return f}}
function evaluate(url:string,title:string,text:string,sourceName:string,sourceCompany:string):DiscoveryCandidateInput|null{const t=`${title} ${text}`.toLowerCase();if(provider.test(t))return null;let best:{name:string;hits:string[]}|null=null;for(const[n,a]of needs){const h=matched(t,a);if(h.length&&(!best||h.length>best.hits.length))best={name:n,hits:h}}if(!best)return null;const strong=matched(t,strongBuyer),project=matched(t,projectBuyer);const strongFit=best.hits.length>=2||project.length>=1;if(!strong.length&&!strongFit)return null;const co=company(url,sourceCompany),intent=[...strong,...project].slice(0,6),kind=strong.length?"A — explicit buyer opportunity":"B — strong-fit public work signal";return{company:co,division:"Engineering",service:best.name,website:(()=>{try{return new URL(url).origin}catch{return undefined}})(),sourceName:`${kind} — ${sourceName}`,sourceUrl:url,evidence:`${kind}. ${title||co}. Need detected: ${best.name}. Relevant terms: ${best.hits.slice(0,5).join(", ")}${intent.length?`. Project/buyer signals: ${intent.join(", ")}`:""}. ${text.slice(0,1200)}`}}
export async function searchMechanicalLeads(sources:{name:string;url:string;source_type:string}[]){const out:DiscoveryCandidateInput[]=await searchBuyerIntent("Engineering"),seen=new Set<string>(),keys=new Set(out.map(c=>`${c.company.toLowerCase()}|${(c.service||"").toLowerCase()}`));for(const s of sources.slice(0,30)){const root=await crawlPage(s.url);if(!root)continue;const pages=[root];for(const l of root.links.filter(x=>follow.test(x)).slice(0,16)){if(seen.has(l))continue;seen.add(l);const p=await crawlPage(l);if(p)pages.push(p)}for(const p of pages){const c=evaluate(p.url,p.title,p.text,`Seeded company research — ${s.name}`,s.name);if(!c)continue;const k=`${c.company.toLowerCase()}|${(c.service||"").toLowerCase()}`;if(keys.has(k))continue;keys.add(k);out.push(c)}}return out.slice(0,100)}
