import type {DiscoveryCandidateInput} from "./discovery";
import {crawlPage} from "./keyless-crawler";

const needs=[
 ["Custom software / internal tools",["custom software","internal tool","internal application","business application","software development","application development"]],
 ["Workflow / business process automation",["workflow automation","business process automation","process automation","manual process","approval workflow","document workflow","power automate"]],
 ["CRM / customer portal",["crm","customer portal","client portal","salesforce","customer relationship management","partner portal"]],
 ["Web / mobile application",["web application","mobile application","mobile app","react","next.js","flutter","ios app","android app"]],
 ["Integration / API automation",["api integration","system integration","data integration","integration platform","erp integration","api development","middleware"]],
 ["Dashboard / reporting",["dashboard","business intelligence","reporting portal","analytics platform","power bi","data visualization"]],
 ["Field service / scheduling system",["field service","dispatch software","scheduling system","work order system","service management","route scheduling"]],
 ["Legacy modernization / digital transformation",["legacy system","modernization","digital transformation","system replacement","application modernization","cloud migration"]],
] as const;
const buyer=["rfp","rfq","request for proposal","request for quote","seeking","looking for","vendor","contractor","consultant","implementation partner","project","initiative","modernization","replace","upgrade","integrate","migration","hiring","opening","job","career","digital transformation","new system","manual process"];
const provider=["we build custom software","our software development services","software development company","custom software company","our app development services","we specialize in software development","technology consulting services"];
const follow=/(career|jobs?|myworkdayjobs|workday|greenhouse|lever|icims|smartrecruiters|jobvite|successfactors|oraclecloud|news|press|project|digital|technology|software|application|automation|integration|crm|portal|data|analytics|rfp|rfq|bid|procurement)/i;
const contactFollow=/(contact|about|leadership|leaders|team|people|management|executive|technology|information|digital|operations|office|directory)/i;
const roleTerms=["chief information officer","cio","chief technology officer","cto","vp information technology","vice president information technology","vice president of information technology","vp technology","vice president technology","director of information technology","it director","director of technology","director of applications","applications director","director of business systems","business systems director","director of digital transformation","digital transformation director","director of operations","operations director","general manager","president"];
const badEmail=/(noreply|no-reply|privacy|abuse|webmaster|careers|jobs|recruiting|recruitment|investor|media|press|support|help|legal|security)/i;
const badName=/^(Chief Information Officer|Chief Technology Officer|CIO|CTO|IT Director|Director of Information Technology|Director of Technology|Director of Applications|Applications Director|Director of Business Systems|Business Systems Director|Director of Digital Transformation|Digital Transformation Director|Director of Operations|Operations Director|General Manager|President|Vice President|Senior Vice President|Contact Us|About Us)$/i;
function matched(text:string,terms:readonly string[]){return terms.filter(x=>text.includes(x));}
function company(url:string,fallback:string){try{const h=new URL(url).hostname.replace(/^www\./,"");if(/(workday|myworkdayjobs|greenhouse|lever|icims|smartrecruiters|jobvite|successfactors|oraclecloud)/i.test(h))return fallback;return h}catch{return fallback}}
function baseHost(url:string){try{return new URL(url).hostname.replace(/^www\./,"").toLowerCase()}catch{return ""}}
function sameCompanyEmail(email:string,host:string){const d=email.split("@")[1]?.toLowerCase()||"";return !!d&&(d===host||d.endsWith(`.${host}`)||host.endsWith(`.${d}`));}
function validName(value:string){const v=value.trim();if(badName.test(v))return false;const words=v.split(/\s+/);if(words.length<2||words.length>4)return false;if(words.some(w=>/^(chief|officer|vice|president|director|manager|technology|information|digital|applications|systems|operations|general|contact|about)$/i.test(w)))return false;return true;}
function namesNear(text:string){const names:string[]=text.match(/\b[A-Z][a-z]+(?:\s+[A-Z][a-z.'-]+){1,3}\b/g)??[];return names.filter(validName);}
function contactName(text:string){const lower=text.toLowerCase();for(const role of roleTerms){const i=lower.indexOf(role);if(i<0)continue;const before=text.slice(Math.max(0,i-220),i),after=text.slice(i+role.length,Math.min(text.length,i+role.length+220));const a=namesNear(before),b=namesNear(after);const n=a.at(-1)??b[0];if(n)return n;}return undefined;}
function contactForEmail(context:string,email:string){const i=context.toLowerCase().indexOf(email.toLowerCase());const around=i>=0?context.slice(Math.max(0,i-350),Math.min(context.length,i+email.length+350)):context;const n=contactName(around);if(n)return n;const names=namesNear(around);return names.length===1?names[0]:undefined;}
async function discoverContact(rootUrl:string){const root=await crawlPage(rootUrl);if(!root)return{};const host=baseHost(root.url),pages=[root],seen=new Set<string>([root.url]);for(const link of root.links.filter(x=>contactFollow.test(x)).slice(0,16)){if(seen.has(link))continue;seen.add(link);const p=await crawlPage(link);if(!p)continue;pages.push(p);for(const deep of p.links.filter(x=>contactFollow.test(x)).slice(0,6)){if(seen.has(deep)||pages.length>=24)continue;seen.add(deep);const d=await crawlPage(deep);if(d)pages.push(d);}}
 let fallbackName:string|undefined;
 for(const p of pages){if(!fallbackName)fallbackName=contactName(p.text);for(const ec of p.emailContexts){const email=ec.email.toLowerCase();if(!sameCompanyEmail(email,host)||badEmail.test(email))continue;return{contactEmail:email,contactName:contactForEmail(ec.context,email)};}}
 return{contactName:fallbackName};}
function evaluate(url:string,title:string,text:string,sourceName:string,sourceCompany:string):DiscoveryCandidateInput|null{const t=`${title} ${text}`.toLowerCase();let best:{name:string;hits:string[]}|null=null;for(const [name,terms]of needs){const h=matched(t,terms);if(h.length&&(!best||h.length>best.hits.length))best={name,hits:h};}if(!best)return null;const buyerHits=matched(t,buyer),providerHits=matched(t,provider);if(providerHits.length>=2&&buyerHits.length===0)return null;if(buyerHits.length===0&&best.hits.length<2)return null;const co=company(url,sourceCompany);const evidence=`${title||co}. Need detected: ${best.name}. Evidence terms: ${best.hits.slice(0,6).join(", ")}${buyerHits.length?`. Buyer intent: ${buyerHits.slice(0,6).join(", ")}`:". Buyer intent not yet confirmed"}. ${text.slice(0,1200)}`;return{company:co,division:"Software",service:best.name,website:(()=>{try{return new URL(url).origin}catch{return undefined}})(),sourceName,sourceUrl:url,evidence};}
export async function searchSoftwareLeads(sources:{name:string;url:string;source_type:string}[]){const out:DiscoveryCandidateInput[]=[],seen=new Set<string>(),candidateKeys=new Set<string>();for(const source of sources.slice(0,30)){const root=await crawlPage(source.url);if(!root)continue;const pages=[root];for(const link of root.links.filter(x=>follow.test(x)).slice(0,14)){if(seen.has(link))continue;seen.add(link);const p=await crawlPage(link);if(!p)continue;pages.push(p);for(const deep of p.links.filter(x=>follow.test(x)).slice(0,10)){if(seen.has(deep)||pages.length>=30)continue;seen.add(deep);const d=await crawlPage(deep);if(d)pages.push(d);}}
 let contact:Partial<DiscoveryCandidateInput>|null=null;
 for(const p of pages){if(seen.has(`soft-eval:${p.url}`))continue;seen.add(`soft-eval:${p.url}`);const c=evaluate(p.url,p.title,p.text,`Software v1 — ${source.name}`,source.name);if(!c)continue;const key=`${c.company.trim().toLowerCase()}|${(c.service||"").trim().toLowerCase()}`;if(candidateKeys.has(key))continue;candidateKeys.add(key);if(contact===null)contact=source.source_type==="Company Website/Careers"?await discoverContact(source.url):{};out.push({...c,...contact});}}
 return out.slice(0,100);}
