import type {DiscoveryCandidateInput,Division} from "./discovery";
import {crawlPage,parseSeedList} from "./keyless-crawler";

const engineering=["solidworks","autodesk inventor","autocad","mechanical design","cad designer","cad drafter","mechanical drafter","fabrication drawing","shop drawing","equipment design","new production line","new facility","plant expansion","engineering backlog"];
const software=["manual process","spreadsheet","excel","scheduling","dispatch","work order","crm","customer portal","employee portal","field service","workflow automation","api integration","quickbooks integration","digital transformation","legacy system","multiple locations"];
const paths=["/careers","/jobs","/news","/press","/about/news","/company/news"];
function hits(t:string,a:string[]){return a.filter(x=>t.includes(x));}
function name(url:string){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return"Unknown company"}}
function candidate(url:string,title:string,text:string):DiscoveryCandidateInput|null{const lower=text.toLowerCase(),e=hits(lower,engineering),s=hits(lower,software);if(!e.length&&!s.length)return null;const division:Division=e.length>=s.length?"Engineering":"Software";const matched=(division==="Engineering"?e:s).slice(0,6);return{company:name(url),division,service:division==="Engineering"?"Company engineering demand signal":"Company software/automation demand signal",website:(()=>{try{return new URL(url).origin}catch{return undefined}})(),sourceName:"Company Website/Careers (Keyless)",sourceUrl:url,evidence:`${title}. Public company page matched: ${matched.join(", ")}. ${text.slice(0,900)}`};}
export async function searchCompanySignalsKeyless(seedValue:string|undefined|null){const seeds=parseSeedList(seedValue),out:DiscoveryCandidateInput[]=[],seen=new Set<string>();for(const seed of seeds){let origin:string;try{origin=new URL(seed).origin}catch{continue}const urls=[seed,...paths.map(p=>origin+p)];for(const url of urls){if(seen.has(url))continue;seen.add(url);const page=await crawlPage(url);if(!page)continue;const c=candidate(page.url,page.title,page.text);if(c)out.push(c);for(const link of page.links.filter(x=>/(career|jobs|news|press|expansion|project)/i.test(x)).slice(0,3)){if(seen.has(link))continue;seen.add(link);const child=await crawlPage(link);if(!child)continue;const cc=candidate(child.url,child.title,child.text);if(cc)out.push(cc);}}}return out.slice(0,60);}
