import type {DiscoveryCandidateInput,Division} from "./discovery";
import {crawlPage,parseSeedList} from "./keyless-crawler";

const engineering=["mechanical engineering","cad","drafting","fabrication drawing","shop drawing","structural engineering","equipment design","autocad","inventor","solidworks"];
const software=["custom software","software development","crm","portal","web application","workflow automation","field service","integration","erp","scheduling software","digital transformation"];
const intent=["rfp","rfq","request for proposal","request for qualifications","request for quote","bid","solicitation","procurement","vendor"];
function hits(t:string,a:string[]){return a.filter(x=>t.includes(x));}
function buyer(url:string){try{return new URL(url).hostname.replace(/^www\./,"")}catch{return"Public buyer"}}
function evaluate(url:string,title:string,text:string):DiscoveryCandidateInput|null{const lower=`${title} ${text}`.toLowerCase(),i=hits(lower,intent);if(!i.length)return null;const e=hits(lower,engineering),s=hits(lower,software);if(!e.length&&!s.length)return null;const division:Division=e.length>=s.length?"Engineering":"Software";const need=(division==="Engineering"?e:s).slice(0,5);return{company:buyer(url),division,service:title||`${division} RFP/RFQ opportunity`,sourceName:"Selected RFP/RFQ Portal (Keyless)",sourceUrl:url,evidence:`Public procurement page matched ${i.slice(0,3).join(", ")} plus ${need.join(", ")}. ${text.slice(0,1000)}`};}
export async function searchRfpPortalsKeyless(seedValue:string|undefined|null){const seeds=parseSeedList(seedValue),out:DiscoveryCandidateInput[]=[],seen=new Set<string>();for(const seed of seeds){const root=await crawlPage(seed);if(!root)continue;seen.add(root.url);const first=evaluate(root.url,root.title,root.text);if(first)out.push(first);const links=root.links.filter(x=>/(bid|rfp|rfq|solicitation|procurement|opportunit|vendor)/i.test(x)).slice(0,15);for(const link of links){if(seen.has(link))continue;seen.add(link);const page=await crawlPage(link);if(!page)continue;const c=evaluate(page.url,page.title,page.text);if(c)out.push(c);for(const child of page.links.filter(x=>/(bid|rfp|rfq|solicitation|opportunit)/i.test(x)).slice(0,4)){if(seen.has(child))continue;seen.add(child);const p=await crawlPage(child);if(!p)continue;const cc=evaluate(p.url,p.title,p.text);if(cc)out.push(cc);}}}return out.slice(0,80);}
