import{getSettings}from"../../../../lib/db";
export const maxDuration=300;
type StageResult={ok?:boolean;error?:string;results?:any[];summary?:any;verified?:number;updated?:number;ready?:number;linked?:number;directVerified?:number;generalVerified?:number;queued?:number;skipped?:boolean};
async function call(origin:string,path:string,method="GET"):Promise<StageResult>{try{const r=await fetch(`${origin}${path}`,{method,headers:{Accept:"application/json"},cache:"no-store"});const text=await r.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{return{ok:false,error:`${path} returned a non-JSON response (${r.status}). The stage may have timed out or been interrupted by the hosting platform.`}}if(!r.ok)return{...data,ok:false,error:data.error||`${path} failed (${r.status})`};return data}catch(e){return{ok:false,error:e instanceof Error?e.message:`${path} failed`}}}
export async function POST(request:Request){try{const s=await getSettings();if(!s.dryRun)return Response.json({ok:false,error:"Arch AI Client Acquisition is locked to Dry Run. No customer email may be sent from this workflow."},{status:409});const origin=new URL(request.url).origin;
 const engineering=await call(origin,"/api/discovery/mechanical");
 const software=await call(origin,"/api/discovery/software");
 const discoverySucceeded=engineering.ok!==false||software.ok!==false;
 if(!discoverySucceeded)return Response.json({ok:false,dryRun:true,emailSending:false,error:`Discovery could not complete. Engineering: ${engineering.error||"failed"}. Software: ${software.error||"failed"}.`,stages:{engineering,software}},{status:502});
 const enrichment=await call(origin,"/api/discovery/enrich-contacts","POST");
 const promotion=enrichment.ok===false?{ok:false,skipped:true,error:"Promotion skipped because contact enrichment did not complete."}:await call(origin,"/api/discovery/promote-ready","POST");
 const drafts=promotion.ok===false?{ok:false,skipped:true,error:"Draft preparation skipped because safe lead promotion did not complete."}:await call(origin,"/api/outreach/prepare","POST");
 const researched=(engineering.results?.length??0)+(software.results?.length??0),qualified=(engineering.summary?.qualified??0)+(software.summary?.qualified??0),review=(engineering.summary?.review??0)+(software.summary?.review??0),rejected=(engineering.summary?.rejected??0)+(software.summary?.rejected??0);
 const warnings=[engineering,software,enrichment,promotion,drafts].filter(x=>x.ok===false).map(x=>x.error).filter(Boolean);
 return Response.json({ok:true,partial:warnings.length>0,dryRun:true,emailSending:false,summary:{researched,qualified,review,rejected,contactsVerified:(enrichment.verified??enrichment.updated??0),newLeads:promotion.ready??0,existingLeadsLinked:promotion.linked??0,draftsPrepared:drafts.queued??0},warnings,stages:{engineering,software,enrichment,promotion,drafts},message:`AI client search ${warnings.length?"completed with warnings":"complete"}: ${researched} companies/prospects researched, ${qualified} qualified, ${review} research-more/review, ${promotion.directVerified??0} direct and ${promotion.generalVerified??0} general contacts verified, ${drafts.queued??0} outreach drafts prepared. 0 emails sent — Dry Run ON.`});}catch(e){return Response.json({ok:false,dryRun:true,emailSending:false,error:e instanceof Error?e.message:"AI client acquisition failed"},{status:500});}}
