import Shell from "../components/Shell";
import DiscoveryControls from "./DiscoveryControls";
import {getDb,getSettings} from "../../lib/db";
import {queryPlan} from "../../lib/discovery-plan";
export const dynamic="force-dynamic";

function cleanText(v:string){return String(v||"").replace(/Verified operating-company source\.?/gi,"").replace(/\b\S+\.(?:com|net|org|io)\b/gi," ").replace(/https?:\/\/\S+/gi," ").replace(/<[^>]*>/g," ").replace(/\{[\s\S]*$/," ").replace(/\s+/g," ").trim()}
function evidenceSummary(x:any){let t=cleanText(x.evidence||"");t=t.replace(new RegExp(`^${String(x.company||"").replace(/[.*+?^${}()|[\]\\]/g,"\\$&")} appears to be a potential buyer of Arch (engineering|software) services based on company operations and relevant project/workload evidence\\.?\\s*`,`i`),"");t=t.replace(/^(Home\s*\|\s*[^>]+>?\s*)+/i,"").trim();const sentences=t.match(/[^.!?]+[.!?]+/g)||[];const useful=sentences.map((s:string)=>s.trim()).filter((s:string)=>s.length>35&&!/cookie|privacy|copyright|schema|latitude|longitude|postaladdress|openinghours|google\.com/i.test(s));const summary=(useful.slice(0,2).join(" ")||t).trim();return summary.length>420?summary.slice(0,417).replace(/\s+\S*$/,"")+"...":summary||"Public company information confirms this is an operating business relevant to Arch services."}
function qualificationSummary(x:any){const d=String(x.division||"");const service=String(x.service||"").toLowerCase();if(d==="Engineering"){if(/fabricat|drawing/.test(service))return"Good Engineering Prospect: The company's machining or fabrication work is a strong fit for Arch CAD, fabrication drawing and mechanical engineering support.";if(/equipment|machine/.test(service))return"Good Engineering Prospect: The company's equipment and manufacturing work is relevant to Arch mechanical design, CAD and production support.";return"Good Engineering Prospect: The company's operations align with Arch mechanical engineering and CAD support capabilities."}if(/schedul|field service/.test(service))return"Good Software Prospect: The business has operations that may benefit from scheduling, dispatch, work-order and workflow software.";if(/website|ecommerce/.test(service))return"Good Software Prospect: The business has a relevant opportunity for website, ecommerce or customer-experience improvements.";if(/integration/.test(service))return"Good Software Prospect: The business has workflows that may benefit from system integration and automation.";return"Good Software Prospect: The company's operations align with Arch custom software, workflow automation and business-system capabilities."}

export default async function Discovery(){
 const db=getDb(),s=await getSettings(),plan=queryPlan();
 const runs=await db.prepare(`SELECT id,run_key,status,engineering_found,software_found,qualified,rejected,dry_run,started_at,completed_at FROM discovery_runs ORDER BY started_at DESC LIMIT 30`).all<any>();
 const allRuns=runs.results as any[];const eng=allRuns.find(r=>String(r.run_key||"").includes("engineering-prospect-"));const sw=allRuns.find(r=>String(r.run_key||"").includes("software-prospect-"));const latestIds=[eng?.id,sw?.id].filter(Boolean).map(Number);
 const c=latestIds.length?await db.prepare(`SELECT company,division,service,website,contact_name,contact_email,source_name,source_url,evidence,ai_score,decision,decision_reason,created_at,run_id FROM discovery_candidates WHERE run_id IN (${latestIds.map(()=>"?").join(",")}) ORDER BY ai_score DESC,created_at DESC LIMIT 100`).bind(...latestIds).all<any>():{results:[] as any[]};
 return <Shell active="/discovery" dryRun={s.dryRun}><header><div><h1>Arch AI Client Acquisition</h1><p>One AI workflow finds Engineering and Software buyers, researches the opportunity, verifies contacts and prepares personalized outreach for review.</p></div></header>
 <div className="safeBanner"><b>Dry Run:</b> research, qualification, contact verification and draft preparation are allowed. Customer email sending is disabled.</div>
 <article className="panel wide"><div className="panelHead"><div><h2>Find New Clients</h2><p>Click once. Arch AI runs the client-acquisition pipeline automatically. No seed lists, career-source management or separate diagnostic steps are required.</p></div></div><DiscoveryControls/></article>
 <div className="grid"><article className="panel"><div className="panelHead"><div><h2>Engineering Buyer Strategy</h2><p>Manufacturers, OEMs, fabricators, machine builders, industrial equipment companies and contractors.</p></div></div><div className="queryList">{plan.engineering.map(q=><div key={q.label}><b>{q.label}</b><span>{q.query}</span></div>)}</div></article><article className="panel"><div className="panelHead"><div><h2>Software Buyer Strategy</h2><p>Businesses with workflow, quoting, scheduling, production, document-control, field-service, dashboard or integration opportunities.</p></div></div><div className="queryList">{plan.software.map(q=><div key={q.label}><b>{q.label}</b><span>{q.query}</span></div>)}</div></article></div>
 <div className="grid"><article className="panel"><div className="panelHead"><div><h2>Client Discovery Runs</h2><p>Newest research runs appear first</p></div></div>{runs.results.length?<div className="tableWrap"><table><thead><tr><th>Run</th><th>Status</th><th>Eng</th><th>Software</th><th>Qualified</th></tr></thead><tbody>{runs.results.map(r=><tr key={r.id}><td>{r.run_key}</td><td>{r.status}</td><td>{r.engineering_found}</td><td>{r.software_found}</td><td>{r.qualified}</td></tr>)}</tbody></table></div>:<div className="empty">No discovery runs yet.</div>}</article><article className="panel"><div className="panelHead"><div><h2>Safety Mode</h2></div></div><div className="rows"><div><span>Dry Run</span><b>{s.dryRun?"ON":"OFF"}</b></div><div><span>Engineering target</span><b>{s.engineeringTarget}</b></div><div><span>Software target</span><b>{s.softwareTarget}</b></div><div><span>Daily maximum</span><b>{s.totalLimit}</b></div></div></article></div>
 <article className="panel wide"><div className="panelHead"><div><h2>Latest Client Prospects</h2><p>Newest Engineering and Software prospects in plain business language.</p></div></div>{c.results.length?<div className="tableWrap"><table><thead><tr><th>Company</th><th>Division</th><th>Opportunity</th><th>What We Found</th><th>Why It Fits Arch</th><th>Source</th><th>Score</th><th>Decision</th></tr></thead><tbody>{c.results.map((x,i)=><tr key={i}><td><b>{x.company}</b></td><td>{x.division}</td><td>{x.service||"Not specified"}</td><td className="evidenceCell">{evidenceSummary(x)}</td><td className="evidenceCell"><b>{qualificationSummary(x)}</b></td><td>{x.source_url?<a href={x.source_url} target="_blank" rel="noreferrer">View public source</a>:"Public company information"}</td><td><b>{Math.round(Number(x.ai_score||0)*6/100)}/6</b></td><td><span className={`decisionPill ${(x.decision||"").toLowerCase()}`}>{x.decision}</span></td></tr>)}</tbody></table></div>:<div className="empty">No client prospects yet. Click Find New Clients.</div>}</article></Shell>
}
